### PR TITLE
fix(bedrock): keep Converse chat completions working under bearer-token auth

### PR DESCRIPTION
**Pull request by mateo-berri**
## TLDR

Problem this solves:

- Every Bedrock chat completion with a bearer token crashed
- Bearer-token deployments resolve no SigV4 credentials, so they are None
- The Converse handler dereferenced None while preparing the Rust hand-off
- Broken since #37241 on `main` and `litellm_internal_staging`

How it solves it:

- Hand SigV4 keys to the Rust core only when credentials resolved
- The Rust core already reads `api_key` or `AWS_BEARER_TOKEN_BEDROCK` itself
- Type the credentials as optional on the Converse path
- Regression tests cover the Python path and the Rust hand-off

## User Flow

Before: a proxy admin who authenticates to Bedrock with an API key (bearer token) cannot make any chat completion call to a Bedrock model

1. They set `AWS_BEARER_TOKEN_BEDROCK` (no `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`) and add `bedrock/global.anthropic.claude-fable-5-1` with `aws_region_name: us-east-1` to the config
2. They send POST http://localhost:4000/v1/chat/completions with `{"model": "fable-bedrock-global", "messages": [...]}`
3. They get HTTP 400 with `litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'` and a Python traceback, after two retries
4. The same happens with `"stream": true`. `/v1/messages` to the same deployment keeps working, so only the chat completions route is dead

After: the same admin gets normal chat completions back

1. Same config, same env
2. They send the same POST http://localhost:4000/v1/chat/completions
3. They get HTTP 200 with the assistant message and token usage
4. With `"stream": true` they get the SSE chunks ending in `data: [DONE]`

## Relevant issues

Regression introduced by #37241

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added meaningful tests
- [x] The handful of test files covering my change pass locally, e.g. `uv run pytest tests/test_litellm/<your_test_file>.py -v`. Leave the suites (`make test-unit-*`, `make test-unit`) to CI: it finishes in ~15 minutes where a laptop takes an hour or more
- [ ] My PR passes all required CI/CD checks (e.g., lint, schema.d.ts sync check, etc.)
- [x] My PR's scope is as isolated as possible; it only solves 1 specific problem
- [ ] I have received a Greptile **Confidence Score of at least 4/5** before requesting a maintainer review (Greptile reviews automatically once the PR is opened; only comment `@greptileai` to re-request a review after pushing changes)

## Screenshots / Proof of Fix

Setup: proxy started with `python litellm/proxy/proxy_cli.py --config config.yaml --port 4771 --detailed_debug`, with only `AWS_BEARER_TOKEN_BEDROCK` set in the environment (no `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`, or `AWS_PROFILE`). Real Bedrock calls to Claude Fable 5.1

```yaml
model_list:
  - model_name: fable-bedrock-global
    litellm_params:
      model: bedrock/global.anthropic.claude-fable-5-1
      aws_region_name: us-east-1

general_settings:
  master_key: sk-1234
```

Both cases use the same request, with `"stream": true` added for the streaming case

```bash
curl -sS http://127.0.0.1:4771/v1/chat/completions \
  -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
  -d '{"model":"fable-bedrock-global","messages":[{"role":"user","content":"Say hi in five words."}],"max_tokens":64}' \
  -w '\nHTTP %{http_code}\n'
```

#### Non-streaming chat completion

1. Ran the curl above
2. Output:

```
{"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \".../litellm/main.py\", line 5785, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n  File \".../litellm/main.py\", line 4059, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n  File \".../litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=fable-bedrock-global\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
HTTP 400
```

#### Streaming chat completion

1. Ran the curl above with `"stream":true` added to the body and `-N`
2. Output: the same 400 error body as the non-streaming case

```
{"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\n...AttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=fable-bedrock-global\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
HTTP 400
```

#### Non-streaming chat completion

1. Ran the curl above
2. Output:

```
{"id":"chatcmpl-e7cee220-cfdb-43b4-9a93-dbf566b8df32","created":1788297931,"model":"fable-bedrock-global","object":"chat.completion","choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there, how are you?","role":"assistant"}}],"usage":{"completion_tokens":11,"prompt_tokens":16,"total_tokens":27,"completion_tokens_details":{"reasoning_tokens":0,"text_tokens":11},"prompt_tokens_details":{"cached_tokens":0,"text_tokens":16,"cache_write_tokens":0,"cache_creation_tokens":0},"cache_creation_input_tokens":0,"cache_read_input_tokens":0}}
HTTP 200
```

#### Streaming chat completion

1. Ran the curl above with `"stream":true` added to the body and `-N`
2. Output:

```
data: {"id":"chatcmpl-d0a995bd-206e-42d8-9b26-c0a8a4ed79b9","created":1788297943,"model":"fable-bedrock-global","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"Hello","role":"assistant"}}],"provider_specific_fields":{}}

data: {"id":"chatcmpl-d0a995bd-206e-42d8-9b26-c0a8a4ed79b9","created":1788297943,"model":"fable-bedrock-global","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":" there"}}],"provider_specific_fields":{}}

data: {"id":"chatcmpl-d0a995bd-206e-42d8-9b26-c0a8a4ed79b9","created":1788297943,"model":"fable-bedrock-global","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":", n"}}],"provider_specific_fields":{}}

data: {"id":"chatcmpl-d0a995bd-206e-42d8-9b26-c0a8a4ed79b9","created":1788297943,"model":"fable-bedrock-global","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"ice to meet you!"}}],"provider_specific_fields":{}}

data: {"id":"chatcmpl-d0a995bd-206e-42d8-9b26-c0a8a4ed79b9","created":1788297943,"model":"fable-bedrock-global","object":"chat.completion.chunk","choices":[{"finish_reason":"stop","index":0,"delta":{}}],"provider_specific_fields":{}}

data: [DONE]

HTTP 200
```

3. The proxy log shows the requests going to `https://bedrock-runtime.us-east-1.amazonaws.com/model/global.anthropic.claude-fable-5-1/converse` and `.../converse-stream`

## Type

🐛 Bug Fix

### Low

- `get_request_headers` now accepts `credentials: Credentials | None`. Passing None with no bearer token still fails inside botocore SigV4 signing, exactly as before

## Final Attestation

- [x] The tests check the right things, including the edge cases, and regressions in the respective real-world customer use-cases are not possible after this PR

### CODE REVIEW

**Comment by mateo-berri** [comment]
Closing as superseded: #39166 landed the same Rust hand-off guard for bearer-token Converse calls on 2026-09-02.
