### ISSUE TITLE
Sending additional data to triton inference server

### ISSUE THREAD

**Issue by vrvrv** [BerriAI/litellm#7507]
Thank you litellm!

Since version 1.55.8, with the support for the generate endpoint to triton, I attempted to integrate it (I am using the vllm backend on the Triton Inference Server and connecting it to the litellm API endpoint.) 

However, there is one aspect that I find lacking, which I would like to inquire about. Compared to the request data for the officially supported vllm_backend on Triton [link](https://github.com/triton-inference-server/vllm_backend/blob/d061556955b89d538ec53f32c532e2041ce2fc89/src/model.py#L76-L130), only a minimal amount of data is being transmitted. Currently, only `text_input`, `parameters`, and `stream` are being sent, and additional parameters are transmitted by updating parameters. However, it is difficult to send other types of data. I hope the structure of `data_for_triton` can be improved to allow for easier modification of the data.

https://github.com/BerriAI/litellm/blob/b9280528d368aced49cb4d287c57cd0b46168cb6/litellm/llms/triton/completion/transformation.py#L168-L175

**Comment by ghost** [comment]
Hey @vrvrv is that the right spec on triton's code? 

I don't see `parameters` in the vllm_backend, i do see `sampling_parameters`

**Comment by vrvrv** [comment]
@krrishdholakia in the vllm_backend, `parameters` is optional. 
vllm_backend gets `parameters` if `sampling_parameters` is not provided.
https://github.com/triton-inference-server/vllm_backend/blob/d061556955b89d538ec53f32c532e2041ce2fc89/src/model.py#L569-L575

**Comment by Connie120** [comment]
Hello! @vrvrv I'm trying to integrate litellm with Triton+vllm. I'm wondering which version of vllm and litellm are you using? I'm always hitting this "[vllm] Error generating stream: Unexpected keyword argument 'stop_words'" error that even setting additional_drop_params wouldn't help. Any help would be appreciated!

**Comment by ghost** [comment]
Hey @Connie120 are you on v1.67.0.post1?

**Comment by Connie120** [comment]
> Hey [@Connie120](https://github.com/Connie120) are you on v1.67.0.post1?

Hi @krrishdholakia, I'm on 1.67.1, which version do you recommend using?

**Comment by Connie120** [comment]
Nvm, I included the stop_words field in my request because I used to get the formatting error for that field, and I'm still carrying that after upgrading litellm to 1.67.1. Now I saw you fixed it in a PR, and now it works, thanks!
