### PR TITLE
fix(proxy): redact provider keys from pass-through failure tracebacks

### PR DESCRIPTION
**Pull request by mateo-berri**
## TLDR

Problem this solves:

- Failed pass-through calls stored the upstream URL, provider key included, in spend logs
- The same raw traceback reached every failure callback (OTel, Datadog, custom loggers)

How it solves it:

- Error information built for logging now redacts its traceback and error message
- The traceback is redacted once before the failure callbacks get it

## User Flow

Before: a proxy admin reads the failure row of a Gemini pass-through call and finds the real Google API key inside it

1. A developer sends POST https://litellm-domain/gemini/v1beta/models/gemini-3.8-flash:generateContent with `x-goog-api-key: <virtual key>` and a body Google rejects
2. Google's 400 body comes back unchanged (`INVALID_ARGUMENT`), with an `x-litellm-call-id` response header
3. The admin opens GET https://litellm-domain/spend/logs?request_id=<call id> (the same row is on https://litellm-domain/ui/?page=logs)
4. `metadata.error_information.traceback` ends with `Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?key=AIza...'`, the real provider key
5. Anyone who can read spend logs (a viewer role, a logging destination, an exported dashboard) can lift the provider key from that row

After: the same row still names the failing upstream URL, with the key blanked out

1. A developer sends POST https://litellm-domain/gemini/v1beta/models/gemini-3.8-flash:generateContent with `x-goog-api-key: <virtual key>` and a body Google rejects
2. Google's 400 body comes back unchanged (`INVALID_ARGUMENT`), with an `x-litellm-call-id` response header
3. The admin opens GET https://litellm-domain/spend/logs?request_id=<call id> (the same row is on https://litellm-domain/ui/?page=logs)
4. `metadata.error_information.traceback` ends with `Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?REDACTED'`
5. Spend-log readers see which upstream failed and why, and can no longer lift the provider key

## Linear ticket

Resolves LIT-7050

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added meaningful tests
- [x] The handful of test files covering my change pass locally, e.g. `uv run pytest tests/test_litellm/<your_test_file>.py -v`. Leave the suites (`make test-unit-*`, `make test-unit`) to CI: it finishes in ~15 minutes where a laptop takes an hour or more
- [x] My PR passes all required CI/CD checks (e.g., lint, schema.d.ts sync check, etc.)
- [x] My PR's scope is as isolated as possible; it only solves 1 specific problem
- [x] I have received a Greptile **Confidence Score of at least 4/5** before requesting a maintainer review (Greptile reviews automatically once the PR is opened; only comment `@greptileai` to re-request a review after pushing changes)

## Delays in PR merge?

If you're seeing a delay in your PR being merged, ping the LiteLLM Team on [Slack (#pr-review)](https://join.slack.com/t/litellmossslack/shared_invite/zt-3o7nkuyfr-p_kbNJj8taRfXGgQI1~YyA).

## Screenshots / Proof of Fix

Shared setup for both legs: one proxy process with 2 uvicorn workers (`--num_workers 2`), a fresh local Postgres database, the real Google AI Studio key in `GEMINI_API_KEY`, this config:

```yaml
model_list:
  - model_name: gemini-3.8-flash
    litellm_params:
      model: gemini/gemini-3.8-flash
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
```

The check script sends one Gemini pass-through call Google rejects, waits for the spend row, and greps the row for the real key (the key itself is masked in the output below):

```zsh
curl -sS -D headers.txt "http://127.0.0.1:${PORT}/gemini/v1beta/models/gemini-3.8-flash:generateContent" \
  -H "x-goog-api-key: ${LITELLM_MASTER_KEY}" -H 'Content-Type: application/json' \
  -d '{"contents": "not a list"}' -o body.json -w 'HTTP %{http_code}\n'
CALL_ID=$(grep -i '^x-litellm-call-id:' headers.txt | awk '{print $2}' | tr -d '\r')
sleep 15
curl -sS "http://127.0.0.1:${PORT}/spend/logs?request_id=${CALL_ID}" -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" > spend_row.json
python3 -c 'import json,os; row=json.load(open("spend_row.json"))[0]; tb=row["metadata"]["error_information"]["traceback"]; print("\n".join(tb.strip().splitlines()[-3:])); print("REAL PROVIDER KEY ANYWHERE IN ROW:", os.environ["GEMINI_API_KEY"] in json.dumps(row))'
```

For the callback sink, `litellm_settings.callbacks: ["risk_callbacks.instance"]` is added to that config, with `risk_callbacks.py` next to it (trimmed here to the two fields quoted below):

```python
class RiskRecorder(CustomLogger):
    async def async_post_call_failure_hook(self, request_data, original_exception, user_api_key_dict, error_type=None, route=None, traceback_str=None):
        with open("events.jsonl", "a") as fh:
            fh.write(json.dumps({"exception_str": str(original_exception), "traceback_str": traceback_str}) + "\n")

instance = RiskRecorder()
```

The streaming leg is the same script with `:streamGenerateContent?alt=sse` as the route, plus one more grep over the record the callback wrote:

```zsh
python3 -c 'import json,os; ev=json.loads(open("events.jsonl").read().strip().splitlines()[-1]); tb=ev["traceback_str"]; print("exception_str:", ev["exception_str"]); print("\n".join(tb.strip().splitlines()[-3:])); print("REAL PROVIDER KEY IN CALLBACK traceback_str:", os.environ["GEMINI_API_KEY"] in tb)'
```

### Before (bf51dea36b)

1. Proxy booted from the merge base on port 25230 with `--num_workers 2`, then the pass-through call:

```text
HTTP 400
x-litellm-call-id: 20ea5bcd-a96e-4ad4-a94a-9076c1cd503a
{"error": {"code": 400, "message": "Invalid value at 'contents' (type.googleapis.com/google.ai.generativelanguage.v1beta.Content), \"not a list\"", "status": "INVALID_ARGUMENT", ...}}
```

2. `GET /spend/logs?request_id=20ea5bcd-a96e-4ad4-a94a-9076c1cd503a`, last 3 lines of `metadata.error_information.traceback`, then the grep:

```text
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?key=AIza<real key, 39 chars, masked here>'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
REAL PROVIDER KEY ANYWHERE IN ROW: True
```

3. Same proxy with the recording callback loaded, streaming route (`:streamGenerateContent?alt=sse`), same body:

```text
HTTP 400
x-litellm-call-id: 75c2418a-3aab-4879-9717-87454c1a1558
{"error": {"code": 400, "message": "Invalid value at 'contents' (type.googleapis.com/google.ai.generativelanguage.v1beta.Content), \"not a list\"", "status": "INVALID_ARGUMENT", ...}}
```

4. `GET /spend/logs?request_id=75c2418a-3aab-4879-9717-87454c1a1558`, last 3 lines of `metadata.error_information.traceback` and the grep, then the callback's record for the same call:

```text
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:streamGenerateContent?alt=sse&key=AIza<real key, 39 chars, masked here>'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
REAL PROVIDER KEY ANYWHERE IN ROW: True
```

```text
exception_str: 400: Upstream passthrough request failed with status 400
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:streamGenerateContent?alt=sse&key=AIza<real key, 39 chars, masked here>'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
REAL PROVIDER KEY IN CALLBACK traceback_str: True
```

### After (4ec5a6761c)

The only commit since, 27c55a21d9, touches the regression test's type annotations and cannot change proxy behavior, so this proof stands

1. Proxy booted from this PR's tip on port 33402 with `--num_workers 2`, then the same pass-through call:

```text
HTTP 400
x-litellm-call-id: 2e5682e0-8640-4bcc-a7cd-2a8796bf071f
{"error": {"code": 400, "message": "Invalid value at 'contents' (type.googleapis.com/google.ai.generativelanguage.v1beta.Content), \"not a list\"", "status": "INVALID_ARGUMENT", ...}}
```

2. `GET /spend/logs?request_id=2e5682e0-8640-4bcc-a7cd-2a8796bf071f`, last 3 lines of `metadata.error_information.traceback`, then the grep:

```text
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?REDACTED'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
REAL PROVIDER KEY ANYWHERE IN ROW: False
```

3. Same proxy with the recording callback loaded, streaming route (`:streamGenerateContent?alt=sse`), same body:

```text
HTTP 400
x-litellm-call-id: bccee6a4-11d1-4fc6-99b8-859cec5cdf44
{"error": {"code": 400, "message": "Invalid value at 'contents' (type.googleapis.com/google.ai.generativelanguage.v1beta.Content), \"not a list\"", "status": "INVALID_ARGUMENT", ...}}
```

4. `GET /spend/logs?request_id=bccee6a4-11d1-4fc6-99b8-859cec5cdf44`, last 3 lines of `metadata.error_information.traceback` and the grep, then the callback's record for the same call:

```text
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:streamGenerateContent?alt=sse&REDACTED'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
REAL PROVIDER KEY ANYWHERE IN ROW: False
```

```text
exception_str: 400: Upstream passthrough request failed with status 400
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:streamGenerateContent?alt=sse&REDACTED'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
REAL PROVIDER KEY IN CALLBACK traceback_str: False
```

Observations from the run:

- Failure rows carry an empty `model` and `api_base`, before and after alike
- The client response body is Google's own, no key in it either way

## Type

🐛 Bug Fix

### Low

- Every red check is a staging-wide circular-import break older than this branch
  - `misc / Run tests` (4 Python versions) fails on `test_lazy_imports.py::test_star_import_exports_public_api`, and the five red CircleCI jobs die at collection on `cannot import name ... from partially initialized module` (`litellm.cost_calculator`, `config_sync_pubsub`, `bedrock_token_counter`). The same `misc` matrix is red on the merge base bf51dea36b itself, and staging's own pipeline 89211 fails the same five CircleCI jobs after #39121 landed. None of them import the two files this PR touches
- OTel's `exception` span attribute still stamps `str(original_exception)` unredacted
  - `litellm/integrations/opentelemetry.py:936` writes the raw exception string onto the "Failed Proxy Server Request" span while the neighbouring `get_error_information` call now gets the redacted traceback. For pass-through failures the exception is the synthetic `HTTPException("Upstream passthrough request failed with status N")`, so no key reaches this attribute today; it only matters if a future caller hands a real httpx error in as `original_exception`
- `LITELLM_DISABLE_REDACT_SECRETS=true` switches this redaction off too
  - Both new call sites go through `_redact_string` in `litellm/_logging.py`, which returns its input untouched when that env var is set. That matches what the flag already meant for log lines and Slack alerts, but an operator who set it to see raw provider errors in stdout now also gets raw keys back in `LiteLLM_SpendLogs.metadata.error_information` and in every custom logger's `traceback_str`
- The spend-log `error_message` filter no longer matches text that sat inside a redacted span
  - `/spend/logs/ui` and `/spend/logs/v2` filter on `metadata.error_information.error_message` (Prisma `string_contains` at `spend_management_endpoints.py:2572-2577`, SQL `LIKE` at `:2762-2765`), which now reads `REDACTED` where a key or token used to be, so a search for the old literal misses and a search for `REDACTED` matches every redacted row
- The spend-log prompt-leak scanner can redact more of a traceback than before
  - `_redact_prompt_leaks_in_error_string` (`spend_tracking_utils.py:1143-1147`) runs over the already-redacted traceback; when `redact_string` swallows an opening quote (`headers={"api-key": ...}` becomes `headers={"REDACTED}`) the value scanner at `:960-991` loses its closing quote and redacts to the end of the string. Over-redaction only, never a leak

## Final Attestation

- [x] The tests check the right things, including the edge cases, and regressions in the respective real-world customer use-cases are not possible after this PR

---

> [!NOTE]
> **Medium Risk**
> Touches security-sensitive error logging and callback data paths; behavior is limited to applying existing `_redact_string` redaction and is covered by new tests.
> 
> **Overview**
> Stops **real provider API keys** from leaking into spend logs and failure callbacks when pass-through upstream calls fail. `httpx` tracebacks often embed the full upstream URL (including `?key=...`), which previously landed verbatim in `metadata.error_information` and in every `async_post_call_failure_hook` `traceback_str`.
> 
> **Standard logging:** `get_error_information` now runs `_redact_string` on `traceback` and `error_message` before building the payload.
> 
> **Proxy failure hooks:** `post_call_failure_hook` redacts `traceback_str` once up front so custom loggers and integrations receive the same scrubbed string.
> 
> Tests cover both the logging payload path and the proxy callback path using a synthetic Gemini URL with a fake `AIza...` key.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 27c55a21d98627661703de9683a64d6718841824. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: litellm/proxy/utils.py [hunk 1]
```diff
@@ -2586,7 +2588,7 @@ async def post_call_failure_hook(
                             request_data=request_data,
                             user_api_key_dict=user_api_key_dict,
                             original_exception=original_exception,
```
[the remark this answers is not in the document]
Comment (mateo-berri) [reply litellm/proxy/utils.py:2590]: The hook only ever gets the synthetic HTTPException for upstream 4xx/5xx; mid-stream httpx errors never quote the URL (httpx formats it only in raise_for_status).

File: tests/test_litellm/proxy/test_proxy_utils.py [hunk 2]
```diff
@@ -1919,3 +1920,51 @@ def fake_sync_failure(self, *args, **kwargs):
...
 
     assert "test_proxy_utils" in captured["async_traceback"]
+
+
+class _TracebackRecordingLogger(CustomLogger):
+    def __init__(self):
+        super().__init__()
+        self.received_traceback: str | None = None
+
+    async def async_post_call_failure_hook(self, request_data, original_exception, user_api_key_dict, traceback_str=None):
```
[the remark this answers is not in the document]
Comment (mateo-berri) [reply tests/test_litellm/proxy/test_proxy_utils.py]: Typed the hook's parameters and return to match CustomLogger's signature in the follow-up commit, so the override now checks cleanly.

File: tests/test_litellm/proxy/test_proxy_utils.py [hunk 3]
```diff
@@ -1919,3 +1920,51 @@ def fake_sync_failure(self, *args, **kwargs):
...
+    upstream_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini:generateContent?key={provider_key}"
+    response = httpx.Response(400, request=httpx.Request("POST", upstream_url))
+    try:
+        response.raise_for_status()
+    except httpx.HTTPStatusError:
+        upstream_traceback = traceback.format_exc()
+    assert provider_key in upstream_traceback
+
+    recorder = _TracebackRecordingLogger()
+    monkeypatch.setattr(litellm, "callbacks", [recorder])
```
[the remark this answers is not in the document]
Comment (mateo-berri) [reply tests/test_litellm/proxy/test_proxy_utils.py:1961]: post_call_failure_hook iterates litellm.callbacks directly with no injection seam, so monkeypatch (auto-restored) is the narrowest option here.

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
bugbot run

**Review by yucheng-berri — APPROVED** [review]
