### ISSUE TITLE
[Bug] v1.80.11.rc.1: APIConnectionError "'NoneType' object has no attribute 'get'" for OpenAI models

### ISSUE THREAD

**Issue by IceKickr** [BerriAI/litellm#18421]
## Description

LiteLLM v1.80.11.rc.1 fails to proxy certain OpenAI models with `'NoneType' object has no attribute 'get'` error.

## Environment
- LiteLLM version: `v1.80.11.rc.1` (Docker image: `ghcr.io/berriai/litellm-database:main-v1.80.11.rc.1`)
- Python: 3.12.3

### 1. gpt-5-codex - HTTP 400
{'error': {'message': "Invalid request format: litellm.APIConnectionError: APIConnectionError:
OpenAIException - 'NoneType' object has no attribute 'get'.
Received Model Group=gpt-5-codex
Available Model Group Fallbacks=None
LiteLLM Retried: 1 times, LiteLLM Max Retries: 2",
'type': 'invalid_request_error', 'param': None, 'code': '400'}}

### 2. OpenAI Realtime WebSocket - No messages received
Connection opens but no messages are received from `/v1/realtime?model=gpt-4o-realtime-preview`

## Steps to Reproduce

```bash
curl -X POST http://localhost:4000/v1/chat/completions \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model": "gpt-5-codex", "messages": [{"role": "user", "content": "Hello"}]}'
```

## Expected Behavior

Request should be proxied to OpenAI successfully.

## Additional Context

These models work correctly on v1.80.8-stable and 1.80.10.rc.5.

**Comment by Harshit28j** [comment]
> I'm still seeing the issue in v1.80.11-stable.
> 
> `Model gpt-5-codex: HTTP 400 - {'error': {'message': "Invalid request format: litellm.APIConnectionError: APIConnectionError: OpenAIException - 'NoneType' object has no attribute 'get'. Received Model Group=gpt-5-codex\nAvailable Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2", 'type': 'invalid_request_error', 'param': None, 'code': '400'}}`
> 
> `Model gpt-5-pro: HTTP 400 - {'error': {'message': "Invalid request format: litellm.APIConnectionError: APIConnectionError: OpenAIException - 'NoneType' object has no attribute 'get'. Received Model Group=gpt-5-pro\nAvailable Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2", 'type': 'invalid_request_error', 'param': None, 'code': '400'}}
> `
> 
> Which version was this fixed in?

Please checkout this one  https://github.com/BerriAI/litellm/releases/tag/v1.80.15.rc.1 and let me know if you still get this issue
