### ISSUE TITLE
[Bug]: 500 error with Azure Open Ai embedding since 1.41.2-stable

### ISSUE THREAD

**Issue by gregoryboue** [BerriAI/litellm#4726]
### What happened?

Since we upgrade litellm proxy from v1.40.3-stable to v1.41.2-stable, the embedding calls returns 500 it's seems to be the same issue as https://github.com/BerriAI/litellm/issues/3458 .

The problem is when `background_health_checks` is enabled, a call is made to embedding model with a messages content : `'messages': [{'role': 'user', 'content': "Hey how's it going?"}]}` and this lead to server error.

We have the following config.yaml file : 

```yaml
general_settings:
  background_health_checks: true
  health_check_interval: 120

model_list:
  - litellm_params:
      api_base: "https://....."
      api_key: "os.environ/azure-openai-api-key"
      api_version: "2023-07-01-preview"
      model: azure/text-embedding-ada-002
    model_info:
       mode: embedding
    model_name: text-embedding-ada-002
```
The only workaround we found is to set background_health_checks to false

### Relevant log output

```shell
LiteLLM Proxy:ERROR: proxy_server.py:3572 - litellm.proxy.proxy_server.embeddings(): Exception occured - litellm.APIConnectionError: AsyncEmbeddings.create() got an unexpected keyword argument 'messages'
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 2947, in aembedding
     response = await init_response
                ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/litellm/llms/azure.py", line 920, in aembedding
     raise e
   File "/usr/local/lib/python3.11/site-packages/litellm/llms/azure.py", line 898, in aembedding
     response = await openai_aclient.embeddings.create(**data, timeout=timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: AsyncEmbeddings.create() got an unexpected keyword argument 'messages'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 7478, in exception_type
     message=f"{exception_provider} APIConnectionError - {message}",
                ^^^^^^^^^^^^^^^^^^
 UnboundLocalError: cannot access local variable 'exception_provider' where it is not associated with a value
  LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
 initial list of deployments: [{'model_name': 'text-embedding-ada-002', 'litellm_params': {'api_key': '....', 'api_base': 'https://....', 'api_version': '2023-07-01-preview', 'model': 'azure/text-embedding-ada-002', 'messages': [{'role': 'user', 'content': "Hey how's it going?"}]}, 'model_info': {'id': 'e0637b31c43a3363122d38343e0fd4d4c7466b63368a0aaacc1514ae797001d4', 'db_model': False, 'base_model': 'text-embedding-ada-002', 'mode': 'embedding'}}]
 async get cache: cache key: 17-42:cooldown_models; local_only: False
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
@gregoryboue this is fixed here: https://github.com/BerriAI/litellm/pull/4518

**Comment by ishaan-jaff** [comment]
Hey @gregoryboue 

Can we setup a 1:1 support channel? Would like to improve litellm for your use-case 

[LinkedIn](https://www.linkedin.com/in/reffajnaahsi/)
[Discord](https://discord.com/invite/wuPM9dRgDw) (just 👋 wave on #general)
