### ISSUE TITLE
[Bug]: ImportError: cannot import name 'T' from 're' 

### ISSUE THREAD

**Issue by Rishang** [BerriAI/litellm#7311]
### What happened?

I imported the `completion` module to load openai model completion, and this is the error.

My python version: python 3.13

### Relevant log output

```shell
from litellm import completion
  File "/home/noobi/.local/lib/python3.13/site-packages/litellm/__init__.py", line 952, in <module>
    from litellm.litellm_core_utils.litellm_logging import Logging, modify_integration
  File "/home/noobi/.local/lib/python3.13/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 70, in <module>
    from ..integrations.azure_storage.azure_storage import AzureBlobStorageLogger
  File "/home/noobi/.local/lib/python3.13/site-packages/litellm/integrations/azure_storage/azure_storage.py", line 6, in <module>
    from re import S, T
ImportError: cannot import name 'T' from 're' (/usr/lib64/python3.13/re/__init__.py)
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.6

**Comment by ishaan-jaff** [comment]
investigating and working on a fix

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/7314/ 

Also made the following improvements:
- Added a test to ensure litellm works on python 3.13 
- Added ruff rule to prevent unused imports https://github.com/BerriAI/litellm/pull/7313

cc @mskarlin and @jamesbraza

**Comment by Rishang** [comment]
its still happening 

- litellm 1.55.7
- python 3.13

```
Traceback (most recent call last):
  File "/home/noobi/.local/bin/heygpt", line 5, in <module>
    from heygpt.cli import app
  File "/home/noobi/.local/lib/python3.13/site-packages/heygpt/cli.py", line 16, in <module>
    from heygpt.core import (
    ...<6 lines>...
    )
  File "/home/noobi/.local/lib/python3.13/site-packages/heygpt/core.py", line 8, in <module>
    from litellm import completion
  File "/home/noobi/.local/lib/python3.13/site-packages/litellm/__init__.py", line 952, in <module>
    from litellm.litellm_core_utils.litellm_logging import Logging, modify_integration
  File "/home/noobi/.local/lib/python3.13/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 70, in <module>
    from ..integrations.azure_storage.azure_storage import AzureBlobStorageLogger
  File "/home/noobi/.local/lib/python3.13/site-packages/litellm/integrations/azure_storage/azure_storage.py", line 6, in <module>
    from re import S, T
ImportError: cannot import name 'T' from 're' (/usr/lib64/python3.13/re/__init__.py)
```

**Comment by ghost** [comment]
@Rishang this commit is on main but hasn't released yet (working through ci/cd now) it should be out soon in v1.55.8 

You can see the release typically on the merge commit - 

<img width="769" alt="Screenshot 2024-12-20 at 1 02 04 PM" src="https://github.com/user-attachments/assets/e30ab515-6c40-4f05-b452-2f3bc2c5c062" />
