### ISSUE TITLE
[Bug]: Deepseek error on proxy after upgrading to 1.61.13-stable

### ISSUE THREAD

**Issue by gcleaves** [BerriAI/litellm#8834]
### What happened?

Hi. I had Deepseek working yesterday on v1.60.0 of the proxy docker. Today I upgraded to v1.61.13-stable and get the error below when attempting to chat with deekpseek-* .

### Relevant log output

```shell
Error occurred while generating model response. Please try again. Error: Error: 500 litellm.APIConnectionError: APIConnectionError: DeepseekException - 'NoneType' object has no attribute 'rstrip'. Received Model Group=deepseek-chat Available Model Group Fallbacks=None
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.13-stable docker proxy

**Comment by gcleaves** [comment]
maybe i should upgrade to a newer version, i see there are some.... I upgraded to v1.61.13-stable and continue to get the same error.

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/8860
