### PR TITLE
fix: stale router cooldown cache entries

### PR DESCRIPTION
**Pull request by InvisibleMan1306**
## Title

Fix stale router cooldown cache entries

## Relevant issues

Partially addresses #31876

## Specific issue resolved

In a multi-replica LiteLLM deployment using Redis-backed router cache, cooldown state can recover inconsistently across replicas.

The problematic sequence is:

1. One replica writes a deployment cooldown entry to `DualCache` with the configured `cooldown_time` TTL.
2. Another replica reads that cooldown entry from Redis through `DualCache.async_batch_get_cache`.
3. `DualCache` copies the Redis value into that replica's local in-memory cache without preserving the Redis key's remaining TTL.
4. The Redis cooldown key can expire at the configured cooldown time, while the replica-local copied value remains readable for the local cache's default TTL.
5. That replica can continue treating the deployment as cooled down after the configured cooldown window has elapsed, causing one pod to keep filtering a deployment while another pod has already recovered.

This PR fixes that specific stale-local-cache behavior by making `CooldownCache` validate the cooldown payload's own `timestamp + cooldown_time` on every read. A cached payload is ignored once its configured cooldown window has elapsed, even if the surrounding cache still contains the value.

This PR does not implement the broader per-deployment `allowed_fails_policy` feature request in #31876.

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added testing in the `tests/test_litellm/` directory, **Adding at least 1 test is a hard requirement** - [see details](https://docs.litellm.ai/docs/extras/contributing_code)
- [x] I have added a screenshot of my new test passing locally
image

- [ ] My PR passes all unit tests on [`make test-unit`](https://docs.litellm.ai/docs/extras/contributing_code)
- [x] My PR's scope is as isolated as possible, it only solves 1 specific problem

## Type

🐛 Bug Fix
✅ Test

## Changes

- Ignore expired router cooldown payloads based on their embedded `timestamp + cooldown_time`
- Prevent local in-memory cache entries from extending cooldowns beyond the configured cooldown duration
- Add focused mocked tests for sync reads, async reads, and min cooldown calculation

## Validation

- `poetry run pytest tests/test_litellm/router_utils/test_cooldown_cache.py -v`
- `poetry run black --check litellm/router_utils/cooldown_cache.py tests/test_litellm/router_utils/test_cooldown_cache.py`
- `poetry run ruff check litellm/router_utils/cooldown_cache.py tests/test_litellm/router_utils/test_cooldown_cache.py`
- `poetry run mypy litellm/router_utils/cooldown_cache.py --ignore-missing-imports`

## Note

`make lint` currently fails on unrelated repository-wide Black formatting drift before reaching the rest of lint.

`make test-unit` was attempted locally after bootstrapping `pip` into the Poetry environment. It failed on an unrelated existing test:

- `tests/test_litellm/llms/vertex_ai/test_vertex.py::test_completion_pydantic_obj_2`
- Result before stop: `1 failed, 305 passed, 2 skipped, 17 warnings`

### CODE REVIEW

**Comment by InvisibleMan1306** [comment]
Note `make test-unit` failed but on an unrelated test:
```
tests/test_litellm/llms/vertex_ai/test_vertex.py::test_completion_pydantic_obj_2
1 failed, 305 passed, 2 skipped, 17 warnings
```

**Review by yassin-berriai — APPROVED** [review]
