### PR TITLE
fix: coerce server_tool_use dict to ServerToolUse in stream_chunk_builder

### LINKED ISSUE #26153: [Bug]: `completion_cost()` raises `AttributeError` on streaming Anthropic responses with web_search in v1.83.10
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

In v1.83.10, `completion_cost()` raises `AttributeError: 'dict' object has no attribute 'web_search_requests'` when called on a streaming Anthropic response that used `web_search_options`.

The root cause: `stream_chunk_builder` reconstructs `usage.server_tool_use` as a `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check was added in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` that accesses `usage.server_tool_use.web_search_requests` directly (see [`tool_call_cost_tracking.py#L340-L344`](https://github.com/BerriAI/litellm/blob/v1.83.10/litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py#L340-L344)). The same pattern also exists in `get_cost_for_anthropic_web_search` in `anthropic/cost_calculation.py#L131`.

This was working in 1.83.0 because the new `server_tool_use` branch in the guard didn't exist, so `_handle_web_search_cost()` was never reached for streaming Anthropic responses.

### Suggested fix

Either:

1. Coerce `server_tool_use` to `ServerToolUse` in `stream_chunk_builder` when reconstructing usage from streaming chunks (addresses root cause), or
2. Use `getattr(..., 'web_search_requests', None)` or `nested_idx`-style dict/attr tolerant access in the two call sites above.

### Version

litellm==1.83.10 (works in 1.83.0)
Python 3.12

### Steps to Reproduce

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role':'user','content':'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size':'low'},
    stream_options={'include_usage':True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # <class 'dict'>
completion_cost(completion_response=r)  # AttributeError
```

### Expected

`completion_cost()` returns a float (as in 1.83.0).

### Relevant log output

```shell
File .../litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py:343, in response_object_includes_web_search_call
    and usage.server_tool_use.web_search_requests is not None
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

### What part of LiteLLM is this about?

SDK (litellm Python package)

### What LiteLLM version are you on ?

1.83.10

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by Anai-Guo**
## Summary

Fixes #26153

When streaming Anthropic responses with `web_search_options`, `stream_chunk_builder` reconstructs `usage.server_tool_use` as a plain `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` (and `get_cost_for_anthropic_web_search`) accesses `.web_search_requests` as an attribute, causing:

```
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

**Root cause**: In `_calculate_usage_per_chunk`, `server_tool_use` is assigned directly from `usage_chunk.server_tool_use` without checking whether it is already a `ServerToolUse` object or a raw dict.

**Fix**: Apply the same dict→object coercion pattern already used for `prompt_tokens_details` in the same method:

```python
# Before:
server_tool_use = usage_chunk.server_tool_use

# After:
_stu = usage_chunk.server_tool_use
server_tool_use = ServerToolUse(**_stu) if isinstance(_stu, dict) else _stu
```

## Reproduction

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role': 'user', 'content': 'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size': 'low'},
    stream_options={'include_usage': True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # was <class 'dict'>, now ServerToolUse
completion_cost(completion_response=r)  # was AttributeError, now works
```

## Test plan

- [ ] Verify `type(r.usage.server_tool_use)` returns `ServerToolUse` after streaming Anthropic web search response
- [ ] Verify `completion_cost()` no longer raises `AttributeError` for streaming Anthropic responses with `web_search_options`
- [ ] Existing streaming tests continue to pass

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Anai-Guo** [comment]
Closing this — the underlying issue (#26153) has since been fixed on `main` via a different, more robust approach. `litellm/litellm_core_utils/llm_cost_calc/utils.py` now has a `_get_web_search_requests()` helper that tolerantly reads `web_search_requests` whether `server_tool_use` is a `dict`, a `ServerToolUse` instance, or `None` (handling at the consuming site rather than coercing in `stream_chunk_builder`). Since #26153 is closed and this branch is now conflicting, this PR is redundant. Thanks!

🤖 Generated with [Claude Code](https://claude.com/claude-code)
