### PR TITLE
fix(bedrock): stop Converse crashing on bearer-token auth without SigV4 credentials

### LINKED ISSUE #38579: [Bug]: Bedrock bearer-token-only deployments fail /v1/chat/completions and /v1/responses with 'NoneType' object has no attribute 'access_key' since #37241
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

Since #37241 (`bf59b7e23d`, routing Bedrock /chat/completions through the Rust core), a Bedrock deployment that authenticates with only `AWS_BEARER_TOKEN_BEDROCK` (no IAM keys in litellm_params, env, or the botocore credential chain) crashes on every /v1/chat/completions and /v1/responses call with `'NoneType' object has no attribute 'access_key'`. The handler now reads `credentials.access_key` unconditionally to hand the IAM keys to the Rust core, but with bearer auth there are no IAM credentials to resolve, so `credentials` is `None`. The same deployment still works on /v1/messages, which does not go through that handler

Expected: bearer-token-only Bedrock deployments keep working on /v1/chat/completions and /v1/responses like they did before #37241, and like they still do on /v1/messages

### User Flow

Before a (hypothetical) fix: a developer whose gateway authenticates to Bedrock with a bearer token gets a 400 on every chat completion, while the same model answers on the Messages API

1. The proxy admin runs the proxy with `AWS_BEARER_TOKEN_BEDROCK` set and a Bedrock deployment that lists only `model` and `aws_region_name`
2. The developer sends POST http://localhost:4000/v1/chat/completions with `{"model": "bedrock-claude", "messages": [{"role": "user", "content": "Say hello in three words"}]}`
3. They get HTTP 400 `Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'` followed by a Python traceback, after two retries
4. They send POST http://localhost:4000/v1/responses with `{"model": "bedrock-claude", "input": "Say hello in three words"}` and get the same 400
5. They send POST http://localhost:4000/v1/messages with the same prompt and get HTTP 200 with the streamed answer `Hello, world, friend.`

After a (hypothetical) fix: the same proxy answers on every endpoint

1. The proxy admin runs the proxy with `AWS_BEARER_TOKEN_BEDROCK` set and a Bedrock deployment that lists only `model` and `aws_region_name`
2. The developer sends POST http://localhost:4000/v1/chat/completions with `{"model": "bedrock-claude", "messages": [{"role": "user", "content": "Say hello in three words"}]}`
3. They get HTTP 200 with a `chat.completion` object whose message content is the model's three-word greeting
4. They send POST http://localhost:4000/v1/responses with `{"model": "bedrock-claude", "input": "Say hello in three words"}` and get HTTP 200 with a `response` object carrying the greeting
5. They send POST http://localhost:4000/v1/messages with the same prompt and get HTTP 200 with the streamed answer, as before

### Proof the bug occurs

Config the proxy ran with:

```yaml
model_list:
  - model_name: bedrock-claude
    litellm_params:
      model: bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_region_name: us-east-1

general_settings:
  master_key: sk-1234
```

Env vars: `AWS_BEARER_TOKEN_BEDROCK=<redacted>`, `AWS_CONFIG_FILE=/dev/null`, `AWS_SHARED_CREDENTIALS_FILE=/dev/null` (so no IAM credentials resolve from `~/.aws`), `DATABASE_URL=<redacted>`

Version or commit: `40ff01b987` on `litellm_internal_staging` (v1.100.0), proxy started with `python litellm/proxy/proxy_cli.py --config config.yaml --port 28707 --use_v2_migration_resolver`

Commands and their full output:

```
$ curl -sS -i http://127.0.0.1:28707/v1/chat/completions \
    -H 'Authorization: Bearer sk-1234' -H 'Content-Type: application/json' \
    -d '{"model":"bedrock-claude","messages":[{"role":"user","content":"Say hello in three words"}]}'
HTTP/1.1 400 Bad Request
date: Thu, 27 Aug 2026 22:23:48 GMT
server: uvicorn
x-litellm-call-id: 2c4bd186-2b1e-4dce-9613-58b50c2b02d0
x-litellm-timeout: 6000.0
content-length: 1028
content-type: application/json

{"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \"/Users/mateo/Development/litellm/litellm/main.py\", line 5780, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mateo/Development/litellm/litellm/main.py\", line 4058, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mateo/Development/litellm/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n                          ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-claude\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
```

The streaming variant (`"stream": true`) returns the identical 400 body

```
$ curl -sS -i http://127.0.0.1:28707/v1/responses \
    -H 'Authorization: Bearer sk-1234' -H 'Content-Type: application/json' \
    -d '{"model":"bedrock-claude","input":"Say hello in three words"}'
HTTP/1.1 400 Bad Request
date: Thu, 27 Aug 2026 22:24:10 GMT
server: uvicorn
x-litellm-call-id: 4b8ceb5c-3103-419b-be8f-859f9b78e279
x-litellm-model-id: 72faaa58059227bd2bab2e47a0f835d205f72b39993e3af44dcf6cd5891421db
x-litellm-version: 1.100.0
x-litellm-response-cost: 0
x-litellm-key-spend: 0.0
x-litellm-timeout: 600.0
content-length: 1028
content-type: application/json

{"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last): ... File \"/Users/mateo/Development/litellm/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n ... AttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-claude\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
```

Same proxy, same deployment, /v1/messages works:

```
$ curl -sS -i http://127.0.0.1:28707/v1/messages \
    -H 'Authorization: Bearer sk-1234' -H 'Content-Type: application/json' -H 'anthropic-version: 2023-06-01' \
    -d '{"model":"bedrock-claude","max_tokens":32,"stream":true,"messages":[{"role":"user","content":"Say hello in three words"}]}'
HTTP/1.1 200 OK
date: Thu, 27 Aug 2026 22:23:53 GMT
server: uvicorn
x-litellm-call-id: 31042fd9-0511-4117-a6b7-fe82c5c6ed92
x-litellm-model-id: 72faaa58059227bd2bab2e47a0f835d205f72b39993e3af44dcf6cd5891421db
x-litellm-model-name: bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
x-litellm-version: 1.100.0
llm_provider-x-amzn-requestid: b7b2cbb9-6cf0-4ffe-9f38-f46ebdfa4c24
x-litellm-model-group: bedrock-claude
x-litellm-attempted-retries: 0
x-litellm-attempted-fallbacks: 0
content-type: text/event-stream; charset=utf-8
Transfer-Encoding: chunked

event: message_start
data: {"type": "message_start", "message": {"model": "claude-haiku-4-5-20251001", ...}}
...
event: content_block_delta
data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": "Hello,"}}
event: content_block_delta
data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": " world,"}}
event: content_block_delta
data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": " frien"}}
event: content_block_delta
data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": "d."}}
...
event: message_stop
data: {"type": "message_stop", "usage": {"input_tokens": 12, "output_tokens": 6}}
```

Found while working on the /v1/messages mid-stream fallback fix, where a bearer-token-only fallback deployment could not be exercised on /v1/chat/completions because of this crash

### What part of LiteLLM is this about?

Proxy

### What LiteLLM version are you on ?

v1.100.0 (`40ff01b987` on litellm_internal_staging)

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by mateo-berri**
## TLDR

Problem this solves:

- Bedrock Converse crashed whenever only `AWS_BEARER_TOKEN_BEDROCK` was configured
- Every `/v1/chat/completions`, `/v1/responses`, and `/v1/messages` call failed, streaming included
- Regressed in #37241, which read SigV4 keys off credentials boto3 never resolved

How it solves it:

- Only pass SigV4 keys down when boto3 actually resolved a principal
- Bearer auth needs no principal, and both code paths read the token themselves
- Missing credentials without a bearer token now raise botocore's `NoCredentialsError`

## User Flow

Before: a developer whose proxy talks to Bedrock with only a bearer token gets an error back from every Converse call

1. The proxy admin sets `AWS_BEARER_TOKEN_BEDROCK`, leaves every AWS access key and profile unset, and starts the proxy with a `bedrock/converse/...` model
2. The developer sends POST http://localhost:4000/v1/chat/completions with `{"model":"bedrock-haiku","messages":[...]}`
3. They get HTTP 400 with `'NoneType' object has no attribute 'access_key'` after the proxy retried twice
4. The same request with `"stream": true` and POST http://localhost:4000/v1/responses fail the same way

After: the same requests come back with the model's answer

1. The proxy admin sets `AWS_BEARER_TOKEN_BEDROCK`, leaves every AWS access key and profile unset, and starts the proxy with a `bedrock/converse/...` model
2. The developer sends POST http://localhost:4000/v1/chat/completions with `{"model":"bedrock-haiku","messages":[...]}`
3. They get HTTP 200 with the assistant message and real token usage
4. The same request with `"stream": true` streams the chunks and ends with `[DONE]`, and POST http://localhost:4000/v1/responses returns HTTP 200 with the output text

## Relevant issues

Fixes #38579

## Linear ticket

Resolves LIT-5928

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added meaningful tests
- [x] The handful of test files covering my change pass locally, e.g. `uv run pytest tests/test_litellm/<your_test_file>.py -v`. Leave the suites (`make test-unit-*`, `make test-unit`) to CI: it finishes in ~15 minutes where a laptop takes an hour or more
- [x] My PR passes all required CI/CD checks (e.g., lint, schema.d.ts sync check, etc.)
- [x] My PR's scope is as isolated as possible; it only solves 1 specific problem
- [x] I have received a Greptile **Confidence Score of at least 4/5** before requesting a maintainer review (Greptile reviews automatically once the PR is opened; only comment `@greptileai` to re-request a review after pushing changes)

## Delays in PR merge?

If you're seeing a delay in your PR being merged, ping the LiteLLM Team on [Slack (#pr-review)](https://join.slack.com/t/litellmossslack/shared_invite/zt-3o7nkuyfr-p_kbNJj8taRfXGgQI1~YyA).

## Screenshots / Proof of Fix

Shared setup for both runs. `bearer_proxy_config.yaml`:

```yaml
model_list:
  - model_name: bedrock-haiku
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_region_name: us-east-1

general_settings:
  master_key: sk-1234
```

Each leg boots the proxy from its own bootstrapped worktree with 2 uvicorn workers on a random free port (checked with `lsof -nP -iTCP:$PORT -sTCP:LISTEN` first). The environment carries only the bearer token, no AWS access key, session token, or profile, and `HOME` points at an empty directory so no `~/.aws` profile is in reach, the way a container with only `AWS_BEARER_TOKEN_BEDROCK` set runs:

```
export AWS_BEARER_TOKEN_BEDROCK=<bedrock api key>
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE
python litellm/proxy/proxy_cli.py --config bearer_proxy_config.yaml --port $PORT --num_workers 2
```

The SigV4 regression check swaps the bearer token for regular `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` credentials and boots the same way. That test IAM user is not allowed `bedrock:InvokeModel`, so AWS answers 403 naming the user, which shows the request was SigV4-signed and authenticated as that identity (account id redacted, worktree paths in tracebacks shortened to `<worktree>`); it is identical on both sides

Every case below hits the real Bedrock API with `us.anthropic.claude-haiku-4-5-20251001-v1:0`

#### Chat completions

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/chat/completions \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \"<worktree>/litellm/main.py\", line 5785, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/main.py\", line 4059, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n                          ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
   HTTP 400
   ```

#### Streaming chat completions

1. Run

   ```
   curl -s -N -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/chat/completions \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"stream":true,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \"<worktree>/litellm/main.py\", line 5785, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/main.py\", line 4059, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n                          ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
   HTTP 400
   ```

#### Responses API

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/responses \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_output_tokens":64,"input":"say hi in 3 words"}'
   ```

2. Observed

   ```
   {"error":{"message":"Invalid request format: litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \"<worktree>/litellm/main.py\", line 5785, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/main.py\", line 4059, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n                          ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 2","type":"invalid_request_error","param":null,"code":"400"}}
   HTTP 400
   ```

#### Messages API

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/messages \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"error":{"message":"litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \"<worktree>/litellm/main.py\", line 5785, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/main.py\", line 4059, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n                          ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"500"}}
   HTTP 500
   ```

#### Streaming Messages API

1. Run

   ```
   curl -s -N -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/messages \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"stream":true,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"error":{"message":"litellm.APIConnectionError: 'NoneType' object has no attribute 'access_key'\nTraceback (most recent call last):\n  File \"<worktree>/litellm/main.py\", line 5785, in completion\n    response = _complete_bedrock(_dispatch_ctx)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/main.py\", line 4059, in _complete_bedrock\n    response = bedrock_converse_chat_completion.completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<worktree>/litellm/llms/bedrock/chat/converse_handler.py\", line 377, in completion\n    (\"aws_access_key_id\", credentials.access_key),\n                          ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'access_key'\n. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"500"}}
   HTTP 500
   ```

#### SigV4 regression check (AWS keys, no bearer token)

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/chat/completions \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"error":{"message":"litellm.PermissionDeniedError: BedrockException - {\"Message\":\"User: arn:aws:iam::<account id>:user/litellm-lit6341-proxy is not authorized to perform: bedrock:InvokeModel on resource: arn:aws:bedrock:us-east-1:<account id>:inference-profile/us.anthropic.claude-haiku-4-5-20251001-v1:0 because no identity-based policy allows the bedrock:InvokeModel action\"}. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"403"}}
   HTTP 403
   ```

#### Chat completions

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/chat/completions \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"id":"chatcmpl-e656c2f6-bc20-4986-8401-dff03ca0a177","created":1788325523,"model":"bedrock-haiku","object":"chat.completion","choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi, how's it?","role":"assistant"}}],"usage":{"completion_tokens":9,"prompt_tokens":14,"total_tokens":23,"completion_tokens_details":{"reasoning_tokens":0,"text_tokens":9},"prompt_tokens_details":{"cached_tokens":0,"text_tokens":14,"cache_write_tokens":0,"cache_creation_tokens":0},"cache_creation_input_tokens":0,"cache_read_input_tokens":0}}
   HTTP 200
   ```

#### Streaming chat completions

1. Run

   ```
   curl -s -N -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/chat/completions \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"stream":true,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   data: {"id":"chatcmpl-c8bb23bb-2b69-47ed-9825-dfbe97e94ac4","created":1788325524,"model":"bedrock-haiku","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"Hi there","role":"assistant"}}],"provider_specific_fields":{}}

   data: {"id":"chatcmpl-c8bb23bb-2b69-47ed-9825-dfbe97e94ac4","created":1788325524,"model":"bedrock-haiku","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":" friend"}}],"provider_specific_fields":{}}

   data: {"id":"chatcmpl-c8bb23bb-2b69-47ed-9825-dfbe97e94ac4","created":1788325524,"model":"bedrock-haiku","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"!"}}],"provider_specific_fields":{}}

   data: {"id":"chatcmpl-c8bb23bb-2b69-47ed-9825-dfbe97e94ac4","created":1788325524,"model":"bedrock-haiku","object":"chat.completion.chunk","choices":[{"finish_reason":"stop","index":0,"delta":{}}],"provider_specific_fields":{}}

   data: [DONE]

   HTTP 200
   ```

#### Responses API

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/responses \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_output_tokens":64,"input":"say hi in 3 words"}'
   ```

2. Observed

   ```
   {"id":"resp_h8u7PTuW8i5sBXSM6eEEVNYpB_lLDAmqZCHk1wEimBfRoIPVgRxzxGR0IHjSU-BosoR6wCSBolrEBsavvN-ml6TSI5oIrVXQejzByGtmLOt5mxxpOHuVofb2UW_oXC8HLNCVDWngSMaJUbKlpUbQ8ip_Q5Gg9fHdnuqjxD8YtvbhtQ3Or3j6DxSmHXNAyuwIwJgNEnQ-r3c3fJKVv7UwY0HUw0CxHcbtfDaZhK3AkoWZwYF5-wFa2SMpAjb_H_j9dxIgo8y6141jTDhMBbn-jsiPBXGWLLPTRmnFcpyBtPJc_HMYAva2LFRjVWkdpFEsSCeG5-QiANTlbDWLVXY_6jarBwFUotXHoZ-mAyYeq8ylU2BnFxHZEJS0VMPl5_cPiIOkzmDBRFXARTtX5C7xRdp90SJ1DVT-Wv9VUTTuadQ3rF1nhOSZYE1OmivdXZf_4ENOhjHQ","created_at":1788325525,"error":null,"incomplete_details":null,"instructions":null,"metadata":{},"model":"bedrock-haiku","object":"response","output":[{"type":"message","id":"msg_7ff34545-644c-4e50-96f4-ed22d4f46595","status":"completed","role":"assistant","content":[{"type":"output_text","text":"Hey there friend!","annotations":[]}],"phase":null}],"parallel_tool_calls":false,"temperature":0.0,"tool_choice":"auto","tools":[],"top_p":null,"max_output_tokens":null,"previous_response_id":null,"reasoning":null,"status":"completed","text":{},"truncation":null,"usage":{"input_tokens":14,"input_tokens_details":{"audio_tokens":null,"cached_tokens":0,"text_tokens":14,"cache_write_tokens":0},"output_tokens":7,"output_tokens_details":{"audio_tokens":null,"reasoning_tokens":0,"text_tokens":7},"total_tokens":21,"cost":null},"user":null,"store":null}
   HTTP 200
   ```

#### Messages API

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/messages \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"id":"chatcmpl-f8fa265d-36fb-4f1c-8bb3-a8040d4538a1","type":"message","role":"assistant","model":"bedrock-haiku","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":10},"content":[{"type":"text","text":"Hey, how's it going?"}],"stop_reason":"end_turn"}
   HTTP 200
   ```

#### Streaming Messages API

1. Run

   ```
   curl -s -N -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/messages \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"stream":true,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   event: message_start
   data: {"type":"message_start","message":{"id":"msg_3f3b2033-c7c3-4215-ae42-851fcec92d67","type":"message","role":"assistant","content":[],"model":"bedrock-haiku","stop_reason":null,"stop_sequence":null,"usage":{"input_tokens":0,"output_tokens":0,"cache_creation_input_tokens":0,"cache_read_input_tokens":0}}}

   event: content_block_start
   data: {"type": "content_block_start", "index": 0, "content_block": {"type": "text", "text": ""}}

   event: content_block_delta
   data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": "Hey"}}

   event: content_block_delta
   data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": " there"}}

   event: content_block_delta
   data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": ","}}

   event: content_block_delta
   data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": " friend"}}

   event: content_block_delta
   data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": "!"}}

   event: content_block_stop
   data: {"type": "content_block_stop", "index": 0}

   event: message_delta
   data: {"type": "message_delta", "delta": {"stop_reason": "end_turn"}, "usage": {"input_tokens": 14, "output_tokens": 8}}

   event: message_stop
   data: {"type": "message_stop"}

   HTTP 200
   ```

#### SigV4 regression check (AWS keys, no bearer token)

1. Run

   ```
   curl -s -w "\nHTTP %{http_code}\n" http://localhost:$PORT/v1/chat/completions \
     -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" \
     -d '{"model":"bedrock-haiku","max_tokens":64,"messages":[{"role":"user","content":"say hi in 3 words"}]}'
   ```

2. Observed

   ```
   {"error":{"message":"litellm.PermissionDeniedError: BedrockException - {\"Message\":\"User: arn:aws:iam::<account id>:user/litellm-lit6341-proxy is not authorized to perform: bedrock:InvokeModel on resource: arn:aws:bedrock:us-east-1:<account id>:inference-profile/us.anthropic.claude-haiku-4-5-20251001-v1:0 because no identity-based policy allows the bedrock:InvokeModel action\"}. Received Model Group=bedrock-haiku\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"403"}}
   HTTP 403
   ```

Observations from the run:

- `/v1/messages` (streaming or not) maps the same crash to HTTP 500, not 400; pre-existing, this PR leaves it alone
- Proxy retries the crash twice before answering; pre-existing, this PR leaves it alone
- SigV4 test principal lacks `bedrock:InvokeModel`; AWS 403 identical before and after

## Type

🐛 Bug Fix

### Low

- Overlaps with #38585 from an external contributor, which fixes the same crash; close whichever lands second
- `get_request_headers` now accepts `credentials=None` and raises botocore's `NoCredentialsError` in the SigV4 branch
- Bearer-only calls still reach the Rust gate, since the Rust core resolves the bearer token itself
- With no bearer token and no SigV4 credentials at all, the error is now a clean 401 `Unable to locate credentials` instead of the 400 `NoneType` crash, the same answer the `bedrock/invoke/...` route already gave
- The SigV4 regression check proves signing and authentication (AWS names the test identity in its 403) but not a 200, since that test IAM user lacks `bedrock:InvokeModel`

## Final Attestation

- [x] The tests check the right things, including the edge cases, and regressions in the respective real-world customer use-cases are not possible after this PR

- [x] 863199c09b passes /live-pr-risk

### CODE REVIEW

**Review by VANDRANKI — COMMENTED** [review]
I read the full diff across `litellm/llms/bedrock/base_aws_llm.py`, `litellm/llms/bedrock/chat/converse_handler.py`, and both new/changed test files, and pulled the surrounding (untouched) code in both files from the PR branch to see the full call path.

The bug: `BedrockConverseLLM.completion()` calls `self.get_credentials(...)`, which returns `None` when only `AWS_BEARER_TOKEN_BEDROCK` is set (bearer-token auth needs no boto3 credential resolution at all). Before this fix, `credentials` was typed as plain `Credentials` and the code building the Rust-bridge handoff (`rust_optional_params`) unconditionally read `credentials.access_key` / `.secret_key` / `.token`, which would crash on `None`. This fix:

- retypes `credentials` as `Credentials | None` everywhere it flows (`get_request_headers`, `async_streaming`, `async_completion`, `completion`, and the local `Final` annotation).
- extracts `_sigv4_principal(credentials)` in `converse_handler.py`, returning an empty `MappingProxyType({})` when `credentials is None` instead of dereferencing it, used to build `rust_optional_params`.
- in `base_aws_llm.py`'s `get_request_headers`, adds `if credentials is None: raise NoCredentialsError()` inside the SigV4 branch.

I checked that this last change doesn't break bearer-token auth going through the legacy (non-Rust) path: I pulled the full body of `get_request_headers` from the PR branch, and it checks `aws_bearer_token` (from `api_key` or `AWS_BEARER_TOKEN_BEDROCK`) *before* the `credentials is None` check, in an `if aws_bearer_token: ... else: ... if credentials is None: raise ...` structure. So a bearer-token call takes the `Authorization: Bearer` branch and never reaches the `None`-credentials guard; that guard only fires in the genuine error case where neither bearer token nor SigV4 credentials are available, which is the same failure botocore itself raises, so it's not a new/foreign error type.

I also checked where the legacy path is reached in `completion()`: it falls through to `get_request_headers(credentials=credentials, ..., api_key=api_key)` either when `serves_via_rust` is false, or when it's true but `rust_response is None` (Rust declined at call time). Both cases pass `api_key` through, so the bearer branch above still applies.

The new tests are well targeted: `test_get_request_headers_without_credentials_or_bearer_token_raises_no_credentials` clears the environment and confirms the exact failure mode (`NoCredentialsError`, not `AttributeError`), and `test_bearer_token_auth_serves_when_boto3_resolves_no_sigv4_credentials` / `test_the_rust_opt_in_needs_no_sigv4_principal` both call the handler with `credentials=None` and assert the bearer token reaches the request and no `aws_*` keys leak into `rust_optional_params`.

I did not execute the suite, but traced every path `credentials=None` can reach and didn't find a remaining dereference. This looks correct and well tested.

This is a community review and does not clear the merge gate.

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
bugbot run

**Review by tin-berri — APPROVED** [review]
