### ISSUE TITLE
[Bug]: LiteLLM Proxy fails to start after uv tool update due to FastAPI get_flat_dependant incompatibility

### ISSUE THREAD

**Issue by rubensadev** [BerriAI/litellm#36922]
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

After running `uv tool update litellm["proxy"]`, LiteLLM was updated to `v1.96.2`.

The LiteLLM proxy was previously working correctly. After the update, the proxy stopped starting.

```text
System: Debian 13 - Trixie
Python: 3.13
```

### User Flow

Before updating, the service worked like a charm. The update of the tool package broke the service.

### Proof the bug occurs

After updating LiteLLM:

```bash
uv tool update litellm["proxy"]
```

the installed version is:

```text
LiteLLM v1.96.2
```

Running:

```bash
litellm --version
```

produces:

```text
Aug 14 14:18:59 litellm systemd[1]: Started litellm.service - LiteLLM Proxy.
Aug 14 14:19:02 litellm uv[13187]: Traceback (most recent call last):
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/proxy_cli.py", line 935, in run_server
Aug 14 14:19:02 litellm uv[13187]:     from .proxy_server import (
Aug 14 14:19:02 litellm uv[13187]:     ...<4 lines>...
Aug 14 14:19:02 litellm uv[13187]:     )
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/proxy_server.py", line 397, in <module>
Aug 14 14:19:02 litellm uv[13187]:     from litellm.proxy.management_endpoints.management_v1 import (
Aug 14 14:19:02 litellm uv[13187]:         router as management_v1_router,
Aug 14 14:19:02 litellm uv[13187]:     )
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/management_endpoints/management_v1/__init__.py", line 5, in <module>
Aug 14 14:19:02 litellm uv[13187]:     from litellm.proxy.management_endpoints.management_v1.spend_logs import (
Aug 14 14:19:02 litellm uv[13187]:         router as spend_logs_router,
Aug 14 14:19:02 litellm uv[13187]:     )
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/management_endpoints/management_v1/spend_logs.py", line 11, in <module>
Aug 14 14:19:02 litellm uv[13187]:     from litellm.proxy.management_endpoints.management_v1.common import (
Aug 14 14:19:02 litellm uv[13187]:     ...<5 lines>...
Aug 14 14:19:02 litellm uv[13187]:     )
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/management_endpoints/management_v1/common.py", line 6, in <module>
Aug 14 14:19:02 litellm uv[13187]:     from fastapi.dependencies.utils import get_flat_dependant
Aug 14 14:19:02 litellm uv[13187]: ImportError: cannot import name 'get_flat_dependant' from 'fastapi.dependencies.utils' (/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/fastapi/dependencies/utils.py)
Aug 14 14:19:02 litellm uv[13187]: During handling of the above exception, another exception occurred:
Aug 14 14:19:02 litellm uv[13187]: Traceback (most recent call last):
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/bin/litellm", line 10, in <module>
Aug 14 14:19:02 litellm uv[13187]:     sys.exit(run_server())
Aug 14 14:19:02 litellm uv[13187]:              ~~~~~~~~~~^^
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 1569, in __call__
Aug 14 14:19:02 litellm uv[13187]:     return self.main(*args, **kwargs)
Aug 14 14:19:02 litellm uv[13187]:            ~~~~~~~~~^^^^^^^^^^^^^^^^^
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 1490, in main
Aug 14 14:19:02 litellm uv[13187]:     rv = self.invoke(ctx)
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 1353, in invoke
Aug 14 14:19:02 litellm uv[13187]:     return ctx.invoke(self.callback, **ctx.params)
Aug 14 14:19:02 litellm uv[13187]:            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 907, in invoke
Aug 14 14:19:02 litellm uv[13187]:     return callback(*args, **kwargs)
Aug 14 14:19:02 litellm uv[13187]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/proxy_cli.py", line 949, in run_server
Aug 14 14:19:02 litellm uv[13187]:     from proxy_server import (
Aug 14 14:19:02 litellm uv[13187]:     ...<4 lines>...
Aug 14 14:19:02 litellm uv[13187]:     )
Aug 14 14:19:02 litellm uv[13187]: ModuleNotFoundError: No module named 'proxy_server'
Aug 14 14:19:02 litellm systemd[1]: litellm.service: Main process exited, code=exited, status=1/FAILURE
Aug 14 14:19:02 litellm systemd[1]: litellm.service: Failed with result 'exit-code'.
Aug 14 14:19:02 litellm systemd[1]: litellm.service: Consumed 3.598s CPU time, 215.8M memory peak.
Aug 14 14:19:08 litellm systemd[1]: litellm.service: Scheduled restart job, restart counter is at 10.
Aug 14 14:19:08 litellm systemd[1]: Started litellm.service - LiteLLM Proxy.
Aug 14 14:19:11 litellm uv[13196]: Traceback (most recent call last):
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/proxy_cli.py", line 935, in run_server
Aug 14 14:19:11 litellm uv[13196]:     from .proxy_server import (
Aug 14 14:19:11 litellm uv[13196]:     ...<4 lines>...
Aug 14 14:19:11 litellm uv[13196]:     )
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/proxy_server.py", line 397, in <module>
Aug 14 14:19:11 litellm uv[13196]:     from litellm.proxy.management_endpoints.management_v1 import (
Aug 14 14:19:11 litellm uv[13196]:         router as management_v1_router,
Aug 14 14:19:11 litellm uv[13196]:     )
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/management_endpoints/management_v1/__init__.py", line 5, in <module>
Aug 14 14:19:11 litellm uv[13196]:     from litellm.proxy.management_endpoints.management_v1.spend_logs import (
Aug 14 14:19:11 litellm uv[13196]:         router as spend_logs_router,
Aug 14 14:19:11 litellm uv[13196]:     )
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/management_endpoints/management_v1/spend_logs.py", line 11, in <module>
Aug 14 14:19:11 litellm uv[13196]:     from litellm.proxy.management_endpoints.management_v1.common import (
Aug 14 14:19:11 litellm uv[13196]:     ...<5 lines>...
Aug 14 14:19:11 litellm uv[13196]:     )
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/management_endpoints/management_v1/common.py", line 6, in <module>
Aug 14 14:19:11 litellm uv[13196]:     from fastapi.dependencies.utils import get_flat_dependant
Aug 14 14:19:11 litellm uv[13196]: ImportError: cannot import name 'get_flat_dependant' from 'fastapi.dependencies.utils' (/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/fastapi/dependencies/utils.py)
Aug 14 14:19:11 litellm uv[13196]: During handling of the above exception, another exception occurred:
Aug 14 14:19:11 litellm uv[13196]: Traceback (most recent call last):
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/bin/litellm", line 10, in <module>
Aug 14 14:19:11 litellm uv[13196]:     sys.exit(run_server())
Aug 14 14:19:11 litellm uv[13196]:              ~~~~~~~~~~^^
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 1569, in __call__
Aug 14 14:19:11 litellm uv[13196]:     return self.main(*args, **kwargs)
Aug 14 14:19:11 litellm uv[13196]:            ~~~~~~~~~^^^^^^^^^^^^^^^^^
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 1490, in main
Aug 14 14:19:11 litellm uv[13196]:     rv = self.invoke(ctx)
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 1353, in invoke
Aug 14 14:19:11 litellm uv[13196]:     return ctx.invoke(self.callback, **ctx.params)
Aug 14 14:19:11 litellm uv[13196]:            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/click/core.py", line 907, in invoke
Aug 14 14:19:11 litellm uv[13196]:     return callback(*args, **kwargs)
Aug 14 14:19:11 litellm uv[13196]:   File "/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/litellm/proxy/proxy_cli.py", line 949, in run_server
Aug 14 14:19:11 litellm uv[13196]:     from proxy_server import (
Aug 14 14:19:11 litellm uv[13196]:     ...<4 lines>...
Aug 14 14:19:11 litellm uv[13196]:     )
Aug 14 14:19:11 litellm uv[13196]: ModuleNotFoundError: No module named 'proxy_server'
```

The subsequent error:

```text
Aug 14 14:19:11 litellm uv[13196]: ImportError: cannot import name 'get_flat_dependant' from 'fastapi.dependencies.utils' (/root/.local/share/uv/tools/litellm/lib/python3.13/site-packages/fastapi/dependencies/utils.py)
ModuleNotFoundError: No module named 'proxy_server'
```

is a secondary failure. `proxy_server.py` is present in the LiteLLM installation, but its import fails because of the FastAPI incompatibility.

The installed FastAPI version can be verified with:

```bash
/root/.local/share/uv/tools/litellm/bin/python -c \
'import fastapi; print(fastapi.__version__)'
```

which reports:

```text
0.141.1
```

The workaround is reproducible:

```bash
uv tool install "litellm[proxy]" \
  --with "fastapi>=0.136.3,<0.140" \
  --force
```

After applying the FastAPI constraint, the LiteLLM proxy starts successfully.

Therefore, the failure is reproducible with:

```text
LiteLLM 1.96.2
FastAPI 0.141.1
```

and disappears when FastAPI is constrained to:

```text
FastAPI >=0.136.3,<0.140
```

### What part of LiteLLM is this about?

Proxy

### What LiteLLM version are you on ?

v1.96.2

**Comment by phuongleeo** [comment]
since I got this error "Vertex_aiException BadRequestError - vertexai import failed please run `pip install -U \"google-cloud-aiplatform>=1.38\"`. Got error: No module named 'vertexai'" 

when tried proxying Vertex AI - Anthropic. 

I encountered same error and #36752 when upgraded to 1.96.2. The workaround for those errors is:

```shell
uv tool install -U 'litellm[proxy]' --with 'fastapi==0.140.6' --with 'google-auth' --with 'google-cloud-aiplatform'
```

**Comment by MilkyWay008** [comment]
The `get_flat_dependant` import error is a FastAPI version mismatch...... litellm 1.96.2 expects the old fastapi.dependencies.utils layout, and `uv tool update` pulled FastAPI 0.141.1 which dropped it. Your pin is the right call, the `--with "fastapi>=0.136.3,<0.140"` keeps uv from re-bumping it on the next update. Worth adding that constraint to the systemd unit or a requirements file so the crash loop doesn't come back.

**Comment by LVerneyEC** [comment]
This issue is very similar to https://github.com/BerriAI/litellm/issues/35763 which should be closed in v1.97.0. Yet, the same issue is still happening on v1.97.0 and requires the `--with` workaround.

**Comment by Griffures** [comment]
Same issue here on 1.97.0, and got to the same conclusions.

IMHO, this sounds like a release management issue more than anything TBH.
