### PR TITLE
fix(ui): read the bundled autorouter presets from disk at test time so image builds pass

### PR DESCRIPTION
**Pull request by mateo-berri**
## TLDR

Problem this solves:

- Every Docker image build off staging fails since #39412 (993766be0e) moved `autorouter_presets.json` under `litellm/proxy/`
- The ui-builder stage copies only `ui/litellm-dashboard/` before `npm run build`
- Two dashboard test files still import `../../../../litellm/proxy/public_endpoints/autorouter_presets.json`
- Next's type check dies with `Cannot find module`, so Image Scan, CircleCI build_docker_database_image, and release image builds all fail

How it solves it:

- The presets test mock reads the catalog from disk at vitest time instead of importing it as a module
- The presets lib test takes the parsed catalog from that mock
- Nothing under `ui/` resolves a module outside the package any more, so the build type check passes
- Tests still track the served catalog; no Dockerfile edits, no test files excluded from the type check

## User Flow

Before: a contributor pushes a commit to any PR against staging and every Docker image build fails, even though the change touched nothing near the dashboard

1. They push a commit and open the PR's checks tab at https://github.com/BerriAI/litellm/pull/39475/checks
2. The three Image Scan jobs (runtime-image, ui-image, image-scan) fail at `npm run build` with `Type error: Cannot find module '../../../../litellm/proxy/public_endpoints/autorouter_presets.json' or its corresponding type declarations.`
3. CircleCI's build_docker_database_image job on the same commit fails with the same line, so the PR waits on it
4. A release engineer running `docker build -t litellm .` at the staging tip hits the same failure in the ui-builder stage, so no RC or stable image can be cut

After: the same push builds every image

1. They push a commit and open the PR's checks tab at https://github.com/BerriAI/litellm/pull/39475/checks
2. The three Image Scan jobs go green: `npm run build` in the ui-builder stage finishes with the usual route table
3. CircleCI's build_docker_database_image job passes
4. `docker build -t litellm .` at the staging tip succeeds

## Linear ticket

Resolves LIT-6783

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added meaningful tests (no new test: the guard is the image build itself, which Image Scan and build_docker_database_image run on every PR; the 139 existing presets tests still pass and still read the real catalog)
- [x] The handful of test files covering my change pass locally: `cd ui/litellm-dashboard && npx vitest run src/lib/autorouter_presets.test.ts src/components/add_model/add_auto_router_tab.test.tsx` -> 2 files, 139 tests passed
- [x] My PR passes all required CI/CD checks (e.g., lint, schema.d.ts sync check, etc.)
- [x] My PR's scope is as isolated as possible; it only solves 1 specific problem
- [x] I have received a Greptile **Confidence Score of at least 4/5** before requesting a maintainer review

## Screenshots / Proof of Fix

Shared setup: all four image Dockerfiles (`Dockerfile`, `docker/Dockerfile.database`, `docker/Dockerfile.non_root`, `ui/Dockerfile`) build the dashboard the same way, copying only `ui/litellm-dashboard/` into the stage and running `npm run build` there, so the proof builds that one stage from the repo root. It is named `ui-builder` in the first three and `builder` in `ui/Dockerfile`

```
docker build --target ui-builder --progress=plain -f Dockerfile -t lit6783-ui-builder .
```

### Before (9e8e486f1c, staging tip)

1. Any push to a PR off staging runs the same `npm run build` inside the ui-builder stage
2. Observed on Image Scan run 33702199775 (#39068 at 0c2be34fb1, same staging base), one line per job:

```
runtime-image  Build runtime image  #25 71.89 Type error: Cannot find module '../../../../litellm/proxy/public_endpoints/autorouter_presets.json' or its corresponding type declarations.
image-scan     Build runtime image  #23 55.80 Type error: Cannot find module '../../../../litellm/proxy/public_endpoints/autorouter_presets.json' or its corresponding type declarations.
ui-image       Build UI image       #18 58.14 Type error: Cannot find module '../../../../litellm/proxy/public_endpoints/autorouter_presets.json' or its corresponding type declarations.
```

### After (bd9d6d442d)

1. The same command at the PR tip
2. Observed:

```
#12 59.85 ✓ Compiled successfully in 59s
#12 59.86   Running TypeScript ...
#12 1979.1   Finished TypeScript in 32.0min ...
#12 1979.2   Collecting page data using 3 workers ...
#12 1983.4 ✓ Generating static pages using 3 workers (51/51) in 2.5s
#12 1983.8 Route (app)
#12 1983.8 ┌ ○ /
#12 1983.8 ├ ○ /_not-found
#12 1983.8 ├ ○ /access-groups
...
#12 DONE 1984.5s
#13 exporting to image
#13 DONE 69.5s
```

3. CircleCI `build_docker_database_image` on this PR at 06d1bf1b3f: passed (https://app.circleci.com/workflow/38eb2fa7-2492-49d1-80fc-37d482ac43de)
4. The Image Scan workflow only auto-runs on Dockerfile-ish paths, which this PR does not touch, so it was dispatched by hand on the branch, once at bd9d6d442d (run 33713142780) and again at 06d1bf1b3f (run 33713954743). Both went green on every job:

```
success  runtime-image
success  ui-image
success  image-scan
success  backend-image
success  gateway-image
success  migrations-image
```

## /live-pr-risk report (06d1bf1b3f)

Verdict: no breaking dependent. The change is confined to two vitest-only modules, and it removes the last module import anywhere in the dashboard that resolved outside the dashboard root

Dependency graph

- `tests/mocks/autoRouterPresets.ts` keeps `BUNDLED_PRESETS`, `LOADED_PRESETS_QUERY` and `useAutoRouterPresets` with the same shapes and adds `BUNDLED_PRESETS_RESPONSE`. Its only importers are `src/components/add_model/add_auto_router_tab.test.tsx` and `src/lib/autorouter_presets.test.ts`, both covered by the `ui-unit-tests` job that is green at this tip
- No non-test module imports the mock, so `fs` never reaches a Next bundle. The ui-builder stage compiles, finishes the TypeScript pass, and exports all 51 static pages
- Data equality: `readFileSync` plus `JSON.parse` on that path produces a value identical to the old module import (compared with `JSON.stringify` over the four families `anthropic_family`, `gemini_family`, `lite`, `openai_family`), so `hydratePresets` gets the same input and every expectation keeps its meaning
- The catalog's Python consumers are untouched. `litellm/proxy/public_endpoints/public_endpoints.py` reads it through `importlib.resources` from the installed package, and `/public/autorouter_presets` still serves the bundled copy

Class sweep

- Resolving every relative module specifier under `src/` and `tests/` shows none escaping `ui/litellm-dashboard/` any more. The only remaining reference to the proxy tree is the `resolve(__dirname, ...)` string, which neither the TypeScript program nor the bundler follows, so the whole class of build breaks is closed and not just this one file

Not verified

- Nothing was skipped. The change has no runtime surface, so there is no proxy leg to drive; the live evidence is the ui-builder image build above, the hand-dispatched Image Scan run, and the green `ui-unit-tests` job at this tip

## Type

🐛 Bug Fix

### Low

- The mock still reads the catalog from the proxy tree at vitest time, so vitest needs a full repo checkout (the old module import needed the same file, so nothing changes for `npm test` or CI)

## Final Attestation

- [x] The tests check the right things, including the edge cases, and regressions in the respective real-world customer use-cases are not possible after this PR
- [x] 06d1bf1b3f passes /live-pr-risk

### CODE REVIEW

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
bugbot run

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
bugbot run

**Comment by mateo-berri** [comment]
#39478 now carries the identical mock fix plus this lib-test rewire, so nothing here is still needed.
