### PR TITLE
fix for importllib compatibility issue for python 3.8

### PR DESCRIPTION
**Pull request by sorokine**
Fix for https://github.com/BerriAI/litellm/issues/2005

was tested to work for python versions 3.8, 3.9, 3.10, 3.11, 3.12

how top test:
```bash
poetry env use 3.8 # or set here python version you want to test against 
poetry install	
poetry shell	
pip install .[proxy]
litellm
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Thanks for the fix @sorokine - really appreciate your help here

**Comment by ffreemt** [comment]
Thanks for the fix. It does not seem to work with Windows 10 Python 3.8.10 though. I follow the instructions exactly.
```
poetry --version
# Poetry (version 1.7.1)

git clone https://github.com/BerriAI/litellm
cd litellm
poetry install
poetry shell
pip install .[proxy]
litellm
```
Still the same AttributeError `importlib.resources' has no attribute 'files'`
```
litellm
Traceback (most recent call last):
  File "C:\mat-dir\playground\github\litellm\.venv\lib\site-packages\litellm\utils.py", line 41, in <module>
    resources.files().joinpath("llms/tokenizers")  # type: ignore
AttributeError: module 'importlib.resources' has no attribute 'files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\mat-dir\playground\github\litellm\.venv\Scripts\litellm.exe\__main__.py", line 4, in <module>
  File "C:\mat-dir\playground\github\litellm\.venv\lib\site-packages\litellm\__init__.py", line 524, in <module>
    from .utils import (
  File "C:\mat-dir\playground\github\litellm\.venv\lib\site-packages\litellm\utils.py", line 45, in <module>
    resources.files(litellm).joinpath("llms/tokenizers")  # for python 3.10
AttributeError: module 'importlib.resources' has no attribute 'files'
```

`from litellm import completion` naturally results in similar errors `AttributeError: module 'importlib.resources' has no attribute 'files'`

**Comment by sorokine** [comment]
I think that https://github.com/BerriAI/litellm does not have this change yet as the PR has not been merged. You can try the same with my fork https://github.com/sorokine/litellm but it is behind the upstream.

**Comment by ishaan-jaff** [comment]
@ffreemt can you can you confirm this fork works for you ?

**Comment by davidmezzetti** [comment]
I just tested the fix from https://github.com/sorokine/litellm locally with Python 3.8 and the error is no longer raised :tada:
