### ISSUE TITLE
[Bug]: Missing Anthropic API Key - A call is being made to anthropic but no key is set either in the environment variables or via params

### ISSUE THREAD

**Issue by sanjay920** [BerriAI/litellm#1560]
### What happened?

Im using the OpenAI proxy server with docker image `ghcr.io/berriai/litellm:main-v1.18.8`

Added a new anthropic model via `/model/new`

I validated the model was added and can see the model added to my mounted config file:
```
litellm_settings:
  cache: true
  drop_params: true
  set_verbose: true
model_list:
- litellm_params:
    api_key: "sk-ant-api03-XYZ"
    model: claude-2.1
  model_info:
    id: dd38ee4d-de06-4842-a7ee-5396e1b62f8c
  model_name: claude-2.1
```

When I try to use openai sdk to do chat completions on claude-2.1 , the openai proxy server bugs out and complains that no API key was passed or was set as an env variable. Looks like a bug but maybe im using it wrong - lmk

### Relevant log output

```shell
2024-01-22 17:12:33 Request to litellm:
2024-01-22 17:12:33 litellm.acompletion(api_key=None, model='claude-2.1', messages=[{'role': 'user', 'content': 'hello'}], caching=True, client=None, timeout=6000, proxy_server_request={'url': 'http://localhost:8002/chat/completions', 'method': 'POST', 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'body': {'messages': [{'role': 'user', 'content': 'hello'}], 'model': 'claude-2.1', 'stream': True}}, metadata={'user_api_key': 'abc', 'user_api_key_user_id': None, 'user_api_key_metadata': {}, 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'endpoint': 'http://localhost:8002/chat/completions', 'model_group': 'claude-2.1', 'deployment': 'claude-2.1', 'caching_groups': None}, request_timeout=600, functions=None, function_call=None, temperature=None, top_p=None, n=None, stream=True, stop=None, max_tokens=None, presence_penalty=None, frequency_penalty=None, logit_bias=None, user=None, response_format=None, seed=None, tools=None, tool_choice=None, logprobs=None, top_logprobs=None, deployment_id=None, base_url=None, api_version=None, model_list=None, model_info={'id': 'dd38ee4d-de06-4842-a7ee-5396e1b62f8c'}, max_retries=0)
2024-01-22 17:12:33 
2024-01-22 17:12:33 
2024-01-22 17:12:33 Initialized litellm callbacks, Async Success Callbacks: ['cache', <litellm.proxy.hooks.parallel_request_limiter.MaxParallelRequestsHandler object at 0x7ffff9e58730>, <litellm.proxy.hooks.max_budget_limiter.MaxBudgetLimiter object at 0x7ffff9e58760>]
2024-01-22 17:12:33 callback: <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7ffff9c46d00>>
2024-01-22 17:12:33 callback: cache
2024-01-22 17:12:33 callback: <litellm.proxy.hooks.parallel_request_limiter.MaxParallelRequestsHandler object at 0x7ffff9e58730>
2024-01-22 17:12:33 callback: <litellm.proxy.hooks.max_budget_limiter.MaxBudgetLimiter object at 0x7ffff9e58760>
2024-01-22 17:12:33 self.optional_params: {}
2024-01-22 17:12:33 litellm.cache: <litellm.caching.Cache object at 0x7ffff9c46fa0>
2024-01-22 17:12:33 kwargs[caching]: True; litellm.cache: <litellm.caching.Cache object at 0x7ffff9c46fa0>
2024-01-22 17:12:33 INSIDE CHECKING CACHE
2024-01-22 17:12:33 Checking Cache
2024-01-22 17:12:33 
2024-01-22 17:12:33 Getting Cache key. Kwargs: {'api_key': None, 'model': 'claude-2.1', 'messages': [{'role': 'user', 'content': 'hello'}], 'caching': True, 'client': None, 'timeout': 6000, 'proxy_server_request': {'url': 'http://localhost:8002/chat/completions', 'method': 'POST', 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'body': {'messages': [{'role': 'user', 'content': 'hello'}], 'model': 'claude-2.1', 'stream': True}}, 'metadata': {'user_api_key': 'abc', 'user_api_key_user_id': None, 'user_api_key_metadata': {}, 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'endpoint': 'http://localhost:8002/chat/completions', 'model_group': 'claude-2.1', 'deployment': 'claude-2.1', 'caching_groups': None}, 'request_timeout': 600, 'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'n': None, 'stream': True, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'logprobs': None, 'top_logprobs': None, 'deployment_id': None, 'base_url': None, 'api_version': None, 'model_list': None, 'model_info': {'id': 'dd38ee4d-de06-4842-a7ee-5396e1b62f8c'}, 'max_retries': 0, 'litellm_call_id': '0d39bed5-ee3b-4297-9b3e-c340c8d16b09', 'litellm_logging_obj': <litellm.utils.Logging object at 0x7ffff9a8cbe0>}
2024-01-22 17:12:33 
2024-01-22 17:12:33 Created cache key: model: claude-2.1messages: [{'role': 'user', 'content': 'hello'}]
2024-01-22 17:12:33 Hashed cache key (SHA-256): fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8
2024-01-22 17:12:33 Get Redis Cache: key: fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8
2024-01-22 17:12:33 Got Redis Cache: key: fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8, cached_response None
2024-01-22 17:12:33 kwargs[caching]: True; litellm.cache: <litellm.caching.Cache object at 0x7ffff9c46fa0>
2024-01-22 17:12:33 INSIDE CHECKING CACHE
2024-01-22 17:12:33 Checking Cache
2024-01-22 17:12:33 
2024-01-22 17:12:33 Getting Cache key. Kwargs: {'model': 'claude-2.1', 'messages': [{'role': 'user', 'content': 'hello'}], 'functions': None, 'function_call': None, 'timeout': 6000, 'temperature': None, 'top_p': None, 'n': None, 'stream': True, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'logprobs': None, 'top_logprobs': None, 'deployment_id': None, 'base_url': None, 'api_version': None, 'api_key': None, 'model_list': None, 'acompletion': True, 'caching': True, 'client': None, 'proxy_server_request': {'url': 'http://localhost:8002/chat/completions', 'method': 'POST', 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'body': {'messages': [{'role': 'user', 'content': 'hello'}], 'model': 'claude-2.1', 'stream': True}}, 'metadata': {'user_api_key': 'abc', 'user_api_key_user_id': None, 'user_api_key_metadata': {}, 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'endpoint': 'http://localhost:8002/chat/completions', 'model_group': 'claude-2.1', 'deployment': 'claude-2.1', 'caching_groups': None}, 'request_timeout': 600, 'model_info': {'id': 'dd38ee4d-de06-4842-a7ee-5396e1b62f8c'}, 'max_retries': 0, 'litellm_call_id': '0d39bed5-ee3b-4297-9b3e-c340c8d16b09', 'litellm_logging_obj': <litellm.utils.Logging object at 0x7ffff9a8cbe0>}
2024-01-22 17:12:33 
2024-01-22 17:12:33 Created cache key: model: claude-2.1messages: [{'role': 'user', 'content': 'hello'}]
2024-01-22 17:12:33 Hashed cache key (SHA-256): fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8
2024-01-22 17:12:33 
2024-01-22 17:12:33 Getting Cache key. Kwargs: {'model': 'claude-2.1', 'messages': [{'role': 'user', 'content': 'hello'}], 'functions': None, 'function_call': None, 'timeout': 6000, 'temperature': None, 'top_p': None, 'n': None, 'stream': True, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'logprobs': None, 'top_logprobs': None, 'deployment_id': None, 'base_url': None, 'api_version': None, 'api_key': None, 'model_list': None, 'acompletion': True, 'caching': True, 'client': None, 'proxy_server_request': {'url': 'http://localhost:8002/chat/completions', 'method': 'POST', 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'body': {'messages': [{'role': 'user', 'content': 'hello'}], 'model': 'claude-2.1', 'stream': True}}, 'metadata': {'user_api_key': 'abc', 'user_api_key_user_id': None, 'user_api_key_metadata': {}, 'headers': {'host': 'localhost:8002', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'OpenAI/Python 1.3.7', 'x-stainless-lang': 'python', 'x-stainless-package-version': '1.3.7', 'x-stainless-os': 'MacOS', 'x-stainless-arch': 'arm64', 'x-stainless-runtime': 'CPython', 'x-stainless-runtime-version': '3.10.12', 'authorization': 'Bearer abc', 'x-stainless-async': 'false', 'content-length': '91'}, 'endpoint': 'http://localhost:8002/chat/completions', 'model_group': 'claude-2.1', 'deployment': 'claude-2.1', 'caching_groups': None}, 'request_timeout': 600, 'model_info': {'id': 'dd38ee4d-de06-4842-a7ee-5396e1b62f8c'}, 'max_retries': 0, 'litellm_call_id': '0d39bed5-ee3b-4297-9b3e-c340c8d16b09', 'litellm_logging_obj': <litellm.utils.Logging object at 0x7ffff9a8cbe0>, 'preset_cache_key': 'fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8'}
2024-01-22 17:12:33 
2024-01-22 17:12:33 Created cache key: model: claude-2.1messages: [{'role': 'user', 'content': 'hello'}]
2024-01-22 17:12:33 Hashed cache key (SHA-256): fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8
2024-01-22 17:12:33 Get Redis Cache: key: fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8
2024-01-22 17:12:33 Got Redis Cache: key: fb1932f45564cc3424f467ce79ba2278a89764eccc0b01da16d9a8b2a6f76ea8, cached_response None
2024-01-22 17:12:33 
2024-01-22 17:12:33 LiteLLM completion() model= claude-2.1; provider = anthropic
2024-01-22 17:12:33 Traceback (most recent call last):
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 962, in completion
2024-01-22 17:12:33     response = anthropic.completion(
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/llms/anthropic.py", line 112, in completion
2024-01-22 17:12:33     headers = validate_environment(api_key, headers)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/llms/anthropic.py", line 83, in validate_environment
2024-01-22 17:12:33     raise ValueError(
2024-01-22 17:12:33 ValueError: Missing Anthropic API Key - A call is being made to anthropic but no key is set either in the environment variables or via params
2024-01-22 17:12:33 
2024-01-22 17:12:33 During handling of the above exception, another exception occurred:
2024-01-22 17:12:33 
2024-01-22 17:12:33 Traceback (most recent call last):
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 275, in acompletion
2024-01-22 17:12:33     response = await loop.run_in_executor(None, func_with_context)  # type: ignore
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2024-01-22 17:12:33     result = self.fn(*self.args, **self.kwargs)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2194, in wrapper
2024-01-22 17:12:33     raise e
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2101, in wrapper
2024-01-22 17:12:33     result = original_function(*args, **kwargs)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1826, in completion
2024-01-22 17:12:33     raise exception_type(
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6777, in exception_type
2024-01-22 17:12:33     raise e
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6752, in exception_type
2024-01-22 17:12:33     raise APIConnectionError(
2024-01-22 17:12:33 litellm.exceptions.APIConnectionError: Missing Anthropic API Key - A call is being made to anthropic but no key is set either in the environment variables or via params
2024-01-22 17:12:33 
2024-01-22 17:12:33 During handling of the above exception, another exception occurred:
2024-01-22 17:12:33 
2024-01-22 17:12:33 Traceback (most recent call last):
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1787, in chat_completion
2024-01-22 17:12:33     response = await llm_router.acompletion(**data)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 487, in acompletion
2024-01-22 17:12:33     raise e
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 481, in acompletion
2024-01-22 17:12:33     response = await self.async_function_with_fallbacks(
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1038, in async_function_with_fallbacks
2024-01-22 17:12:33     raise original_exception
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 966, in async_function_with_fallbacks
2024-01-22 17:12:33     response = await self.async_function_with_retries(*args, **kwargs)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1097, in async_function_with_retries
2024-01-22 17:12:33     raise original_exception
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1055, in async_function_with_retries
2024-01-22 17:12:33     response = await original_function(*args, **kwargs)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 549, in _acompletion
2024-01-22 17:12:33     raise e
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 528, in _acompletion
2024-01-22 17:12:33     response = await litellm.acompletion(
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2433, in wrapper_async
2024-01-22 17:12:33     raise e
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2324, in wrapper_async
2024-01-22 17:12:33     result = await original_function(*args, **kwargs)
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 287, in acompletion
2024-01-22 17:12:33     raise exception_type(
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6777, in exception_type
2024-01-22 17:12:33     raise e
2024-01-22 17:12:33   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5824, in exception_type
2024-01-22 17:12:33     response=original_exception.response,
2024-01-22 17:12:33 AttributeError: 'APIConnectionError' object has no attribute 'response'
2024-01-22 17:12:33 
2024-01-22 17:12:33 LiteLLM: Params passed to completion() {'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'stream': True, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': 0, 'logprobs': None, 'top_logprobs': None, 'custom_llm_provider': 'anthropic', 'model': 'claude-2.1', 'n': None, 'stop': None}
```

**Comment by sanjay920** [comment]
btw anthropic appears to be working in 1.15.3

**Comment by ghost** [comment]
able to repro this problem - working on a fix now

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/fe489ec22b21b096963266dc1e3208255b751174

**Comment by ghost** [comment]
should be live soon in v`1.18.10`

**Comment by ishaan-jaff** [comment]
@sanjay920 can you let us know if this version works for you? https://github.com/BerriAI/litellm/releases/tag/v1.18.11

**Comment by ghost** [comment]
Closing as i believe this is now fixed
