### ISSUE TITLE
[Bug]: `completion_cost()` raises `AttributeError` on streaming Anthropic responses with web_search in v1.83.10

### ISSUE THREAD

**Issue by jph00** [BerriAI/litellm#26153]
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

In v1.83.10, `completion_cost()` raises `AttributeError: 'dict' object has no attribute 'web_search_requests'` when called on a streaming Anthropic response that used `web_search_options`.

The root cause: `stream_chunk_builder` reconstructs `usage.server_tool_use` as a `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check was added in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` that accesses `usage.server_tool_use.web_search_requests` directly (see [`tool_call_cost_tracking.py#L340-L344`](https://github.com/BerriAI/litellm/blob/v1.83.10/litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py#L340-L344)). The same pattern also exists in `get_cost_for_anthropic_web_search` in `anthropic/cost_calculation.py#L131`.

This was working in 1.83.0 because the new `server_tool_use` branch in the guard didn't exist, so `_handle_web_search_cost()` was never reached for streaming Anthropic responses.

### Suggested fix

Either:

1. Coerce `server_tool_use` to `ServerToolUse` in `stream_chunk_builder` when reconstructing usage from streaming chunks (addresses root cause), or
2. Use `getattr(..., 'web_search_requests', None)` or `nested_idx`-style dict/attr tolerant access in the two call sites above.

### Version

litellm==1.83.10 (works in 1.83.0)
Python 3.12

### Steps to Reproduce

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role':'user','content':'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size':'low'},
    stream_options={'include_usage':True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # <class 'dict'>
completion_cost(completion_response=r)  # AttributeError
```

### Expected

`completion_cost()` returns a float (as in 1.83.0).

### Relevant log output

```shell
File .../litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py:343, in response_object_includes_web_search_call
    and usage.server_tool_use.web_search_requests is not None
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

### What part of LiteLLM is this about?

SDK (litellm Python package)

### What LiteLLM version are you on ?

1.83.10

**Comment by ishaan-berri** [comment]
PR opened: https://github.com/BerriAI/litellm/pull/27346

Both root-cause coercion (in `Usage.__init__` and `stream_chunk_builder`) AND defensive dict/pydantic-tolerant access at the two call sites you flagged. Thanks for the great write-up + reproducer — that's why this was a fast fix.

**Comment by DmitriyAlergant** [comment]
Experiencing the same issue. PR https://github.com/BerriAI/litellm/pull/27346 is very welcome, still not merged to main though... Thanks @ishaan-berri
