### PR TITLE
fix: coerce server_tool_use dict to ServerToolUse in stream_chunk_builder

### LINKED ISSUE #26153: [Bug]: `completion_cost()` raises `AttributeError` on streaming Anthropic responses with web_search in v1.83.10
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

In v1.83.10, `completion_cost()` raises `AttributeError: 'dict' object has no attribute 'web_search_requests'` when called on a streaming Anthropic response that used `web_search_options`.

The root cause: `stream_chunk_builder` reconstructs `usage.server_tool_use` as a `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check was added in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` that accesses `usage.server_tool_use.web_search_requests` directly (see [`tool_call_cost_tracking.py#L340-L344`](https://github.com/BerriAI/litellm/blob/v1.83.10/litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py#L340-L344)). The same pattern also exists in `get_cost_for_anthropic_web_search` in `anthropic/cost_calculation.py#L131`.

This was working in 1.83.0 because the new `server_tool_use` branch in the guard didn't exist, so `_handle_web_search_cost()` was never reached for streaming Anthropic responses.

### Suggested fix

Either:

1. Coerce `server_tool_use` to `ServerToolUse` in `stream_chunk_builder` when reconstructing usage from streaming chunks (addresses root cause), or
2. Use `getattr(..., 'web_search_requests', None)` or `nested_idx`-style dict/attr tolerant access in the two call sites above.

### Version

litellm==1.83.10 (works in 1.83.0)
Python 3.12

### Steps to Reproduce

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role':'user','content':'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size':'low'},
    stream_options={'include_usage':True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # <class 'dict'>
completion_cost(completion_response=r)  # AttributeError
```

### Expected

`completion_cost()` returns a float (as in 1.83.0).

### Relevant log output

```shell
File .../litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py:343, in response_object_includes_web_search_call
    and usage.server_tool_use.web_search_requests is not None
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

### What part of LiteLLM is this about?

SDK (litellm Python package)

### What LiteLLM version are you on ?

1.83.10

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by VANDRANKI**
## What

Fixes `AttributeError: 'dict' object has no attribute 'web_search_requests'` raised by `completion_cost()` on streaming Anthropic responses that used `web_search_options`.

Closes #26153.

## Root cause

`stream_chunk_builder` accumulates `server_tool_use` from streaming chunks at:

```python
server_tool_use = usage_chunk.server_tool_use
```

When the Anthropic streaming JSON is deserialized, `usage_chunk.server_tool_use` may be a plain `dict` rather than a `ServerToolUse` pydantic object (pydantic does not auto-coerce nested model fields on a `SafeAttributeModel`). The reconstructed `Usage` object then carries a `dict` for `server_tool_use`.

In v1.83.10, `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` added a direct attribute access:

```python
and usage.server_tool_use.web_search_requests is not None
```

This crashes when `server_tool_use` is a `dict`.

## Fix

Coerce the value to `ServerToolUse` at the point of accumulation in `streaming_chunk_builder_utils.py`:

```python
stu = usage_chunk.server_tool_use
server_tool_use = ServerToolUse(**stu) if isinstance(stu, dict) else stu
```

`ServerToolUse` is already imported in the file. The fix is one-liner and addresses the root cause rather than patching the two call sites that access `.web_search_requests`.

## Test

Added `test_stream_chunk_builder_coerces_server_tool_use_dict_to_object` in `tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py`. The test injects a `dict`-typed `server_tool_use` into a usage chunk and asserts that the rebuilt `Usage` has a proper `ServerToolUse` instance with the correct `web_search_requests` value.

### CODE REVIEW

**Comment by VANDRANKI** [comment]
Thanks for the thorough review - all three issues are valid, addressed in the latest commits:

**1. Coercion undone by `Usage(**returned_usage.model_dump())`**

Added the same coercion guard inside `Usage.__init__` in `litellm/types/utils.py`:

```python
if server_tool_use is not None:
    if isinstance(server_tool_use, dict):
        server_tool_use = ServerToolUse(**server_tool_use)
    self.server_tool_use = server_tool_use
```

Now the coercion happens at construction time regardless of how the `Usage` object is created - whether from streaming accumulation or re-construction via `model_dump()`.

**2. Broken test: `get_combined_usage` -> `calculate_usage`**

Fixed to call the correct method with the right signature:
```python
result = processor.calculate_usage(
    chunks=chunks,
    model="claude-sonnet-4-6",
    completion_output="The otter",
)
```

**3. Dict-style assertion contradicts the fix**

Changed `usage.server_tool_use['web_search_requests']` to `usage.server_tool_use.web_search_requests` - attribute access is now the correct form since `server_tool_use` is guaranteed to be a `ServerToolUse` instance after these changes.
