### ISSUE TITLE
router issue with ooba's WEBUI openai/… : cannot import name 'ExceptionGroup' from anyio._core._exceptions

### ISSUE THREAD

**Issue by chymian** [BerriAI/litellm#1146]
querying llitellm to forward to WEBUI, generates an error. (model: gpt4-32K)
same query to ollama works. (model: coder2)
same query to WEBUI direct works (port 5000)

litellm: 1.14.5 (port 8000, docker, build today)
ubu: 22.04
ooba's WEBUI: thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest (port 5000)

#### CMD
```bash
curl --location 'http://0.0.0.0:8000/v1/chat/completions' --header 'Content-Type: application/json' --data ' {
     "model": "gpt4-32K",
     "messages": [
         {
         "role": "user",
         "content": "where is phousy mountain?"
         }
     ]
     }'|jq
```

#### config
```yaml
model_list:
  - model_name: coder
    litellm_params:
      model: ollama/coder
      api_key: "nothing"
      api_base: http://ollama-GPU1:11434
      max_tokens: 4096

  - model_name: coder2
    litellm_params:
      model: ollama/coder2
      api_key: "nothing"
      api_base: http://ollama-GPU0:11434
      max_tokens: 4096

# running on webui
  - model_name: gpt4-32K
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: "nothing"
      api_base: http://10.11.1.17:5000
      max_tokens: 4096


# Global settings for the litellm module
litellm_settings:
  drop_params: true
  set_verbose: true
# cache:
#   type: redis   # tell litellm to use redis caching
```

#### log

```log
litellm-api  | Collecting uvicorn
litellm-api  |   Downloading uvicorn-0.24.0.post1-py3-none-any.whl.metadata (6.4 kB)
litellm-api  | Collecting fastapi
litellm-api  |   Downloading fastapi-0.105.0-py3-none-any.whl.metadata (24 kB)
litellm-api  | Requirement already satisfied: appdirs in /usr/local/lib/python3.11/site-packages (1.4.4)
litellm-api  | Collecting backoff
litellm-api  |   Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
litellm-api  | Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/site-packages (6.0.1)
litellm-api  | Collecting rq
litellm-api  |   Downloading rq-1.15.1-py2.py3-none-any.whl.metadata (1.6 kB)
litellm-api  | Collecting orjson
litellm-api  |   Downloading orjson-3.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (49 kB)
litellm-api  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.5 MB/s eta 0:00:00
litellm-api  | Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/site-packages (from uvicorn) (8.1.7)
litellm-api  | Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/site-packages (from uvicorn) (0.14.0)
litellm-api  | Collecting anyio<4.0.0,>=3.7.1 (from fastapi)
litellm-api  |   Downloading anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
litellm-api  | Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/site-packages (from fastapi) (2.5.2)
litellm-api  | Collecting starlette<0.28.0,>=0.27.0 (from fastapi)
litellm-api  |   Downloading starlette-0.27.0-py3-none-any.whl.metadata (5.8 kB)
litellm-api  | Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/site-packages (from fastapi) (4.9.0)
litellm-api  | Collecting redis>=4.0.0 (from rq)
litellm-api  |   Downloading redis-5.0.1-py3-none-any.whl.metadata (8.9 kB)
litellm-api  | Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/site-packages (from anyio<4.0.0,>=3.7.1->fastapi) (3.6)
litellm-api  | Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/site-packages (from anyio<4.0.0,>=3.7.1->fastapi) (1.3.0)
litellm-api  | Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.6.0)
litellm-api  | Requirement already satisfied: pydantic-core==2.14.5 in /usr/local/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.14.5)
litellm-api  | Downloading uvicorn-0.24.0.post1-py3-none-any.whl (59 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 5.3 MB/s eta 0:00:00
litellm-api  | Downloading fastapi-0.105.0-py3-none-any.whl (93 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 5.1 MB/s eta 0:00:00
litellm-api  | Downloading rq-1.15.1-py2.py3-none-any.whl (95 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 5.1 MB/s eta 0:00:00
litellm-api  | Downloading orjson-3.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 6.2 MB/s eta 0:00:00
litellm-api  | Downloading anyio-3.7.1-py3-none-any.whl (80 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.9/80.9 kB 5.6 MB/s eta 0:00:00
litellm-api  | Downloading redis-5.0.1-py3-none-any.whl (250 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.3/250.3 kB 5.6 MB/s eta 0:00:00
litellm-api  | Downloading starlette-0.27.0-py3-none-any.whl (66 kB)
litellm-api  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 kB 4.4 MB/s eta 0:00:00
litellm-api  | Installing collected packages: uvicorn, redis, orjson, backoff, anyio, starlette, rq, fastapi
litellm-api  |   Attempting uninstall: anyio
litellm-api  |     Found existing installation: anyio 4.1.0
litellm-api  |     Uninstalling anyio-4.1.0:
litellm-api  |       Successfully uninstalled anyio-4.1.0
litellm-api  | Successfully installed anyio-3.7.1 backoff-2.2.1 fastapi-0.105.0 orjson-3.9.10 redis-5.0.1 rq-1.15.1 starlette-0.27.0 uvicorn-0.24.0.post1
litellm-api  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
litellm-api  | /usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py:48: UserWarning: Installed runtime dependencies for proxy server. Specify these dependencies explicitly with `pip install litellm[proxy]`
litellm-api  |   warnings.warn(
litellm-api  | INFO:     Started server process [8]
litellm-api  | INFO:     Waiting for application startup.
litellm-api  | INFO:     Application startup complete.
litellm-api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
litellm-api  | 
litellm-api  | [1;37m#------------------------------------------------------------#[0m
litellm-api  | [1;37m#                                                            #[0m
litellm-api  | [1;37m#       'This feature doesn't meet my needs because...'       #[0m
litellm-api  | [1;37m#        https://github.com/BerriAI/litellm/issues/new        #[0m
litellm-api  | [1;37m#                                                            #[0m
litellm-api  | [1;37m#------------------------------------------------------------#[0m
litellm-api  | 
litellm-api  |  Thank you for using LiteLLM! - Krrish & Ishaan
litellm-api  | 
litellm-api  | 
litellm-api  | 
litellm-api  | [1;31mGive Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new[0m
litellm-api  | 
litellm-api  | 
litellm-api  | [32mLiteLLM: Proxy initialized with Config, Set models:[0m
litellm-api  | [32m    coder[0m
litellm-api  | [32m    coder2[0m
litellm-api  | [32m    gpt4-32K[0m
litellm-api  | LiteLLM.Router: 
litellm-api  |  Initialized Model List [{'model_name': 'coder', 'litellm_params': {'model': 'ollama/coder-ModelID-ollama/coderhttp://ollama-GPU1:114344096', 'api_key': 'nothing', 'api_base': 'http://ollama-GPU1:11434', 'max_tokens': 4096}, 'model_info': {'id': 'c1f3af09-46de-4aae-92a8-0d1e03defcaa'}}, {'model_name': 'coder2', 'litellm_params': {'model': 'ollama/coder2', 'api_key': 'nothing', 'api_base': 'http://ollama-GPU0:11434', 'max_tokens': 4096}}, {'model_name': 'gpt4-32K', 'litellm_params': {'model': 'openai/gpt-3.5-turbo', 'api_key': 'nothing', 'api_base': 'http://10.11.1.17:5000', 'max_tokens': 4096}}]
litellm-api  | LiteLLM.Router: 
litellm-api  |  Initialized Model List [{'model_name': 'coder', 'litellm_params': {'model': 'ollama/coder-ModelID-ollama/coderhttp://ollama-GPU1:114344096', 'api_key': 'nothing', 'api_base': 'http://ollama-GPU1:11434', 'max_tokens': 4096}, 'model_info': {'id': 'c1f3af09-46de-4aae-92a8-0d1e03defcaa'}}, {'model_name': 'coder2', 'litellm_params': {'model': 'ollama/coder2-ModelID-ollama/coder2http://ollama-GPU0:114344096', 'api_key': 'nothing', 'api_base': 'http://ollama-GPU0:11434', 'max_tokens': 4096}, 'model_info': {'id': '1dc6c374-9193-4e66-a00b-ab447612fddb'}}, {'model_name': 'gpt4-32K', 'litellm_params': {'model': 'openai/gpt-3.5-turbo', 'api_key': 'nothing', 'api_base': 'http://10.11.1.17:5000', 'max_tokens': 4096}}]
litellm-api  | LiteLLM.Router: Initializing OpenAI Client for openai/gpt-3.5-turbo, Api Base:http://10.11.1.17:5000, Api Key:nothing
litellm-api  | LiteLLM.Router: 
litellm-api  |  Initialized Model List [{'model_name': 'coder', 'litellm_params': {'model': 'ollama/coder-ModelID-ollama/coderhttp://ollama-GPU1:114344096', 'api_key': 'nothing', 'api_base': 'http://ollama-GPU1:11434', 'max_tokens': 4096}, 'model_info': {'id': 'c1f3af09-46de-4aae-92a8-0d1e03defcaa'}}, {'model_name': 'coder2', 'litellm_params': {'model': 'ollama/coder2-ModelID-ollama/coder2http://ollama-GPU0:114344096', 'api_key': 'nothing', 'api_base': 'http://ollama-GPU0:11434', 'max_tokens': 4096}, 'model_info': {'id': '1dc6c374-9193-4e66-a00b-ab447612fddb'}}, {'model_name': 'gpt4-32K', 'litellm_params': {'model': 'openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096', 'api_key': 'nothing', 'api_base': 'http://10.11.1.17:5000', 'max_tokens': 4096}, 'model_info': {'id': '822e69a1-0a91-4982-8252-af88ef1572b8'}, 'async_client': <openai.AsyncOpenAI object at 0x7f1c38fe8a10>, 'client': <openai.OpenAI object at 0x7f1c39c00ed0>, 'stream_async_client': <openai.AsyncOpenAI object at 0x7f1c38e85810>, 'stream_client': <openai.OpenAI object at 0x7f1c38ea73d0>}]
litellm-api  | LiteLLM.Router: Intialized router with Routing strategy: simple-shuffle
litellm-api  | 
litellm-api  | 
litellm-api  | [1;34mLiteLLM: Test your local proxy with: "litellm --test" This runs an openai.ChatCompletion request to your proxy [In a new terminal tab][0m
litellm-api  | 
litellm-api  | [1;34mLiteLLM: Curl Command Test for your local proxy
litellm-api  |  
litellm-api  |     curl --location 'http://0.0.0.0:8000/chat/completions' \
litellm-api  |     --header 'Content-Type: application/json' \
litellm-api  |     --data ' {
litellm-api  |     "model": "gpt-3.5-turbo",
litellm-api  |     "messages": [
litellm-api  |         {
litellm-api  |         "role": "user",
litellm-api  |         "content": "what llm are you"
litellm-api  |         }
litellm-api  |     ]
litellm-api  |     }'
litellm-api  |     
litellm-api  | 
litellm-api  |      [0m
litellm-api  | 
litellm-api  | [1;34mDocs: https://docs.litellm.ai/docs/simple_proxy[0m
litellm-api  | 
litellm-api  | final data being sent to completion call: {'model': 'gpt4-32K', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}], 'proxy_server_request': {'url': 'http://0.0.0.0:8000/v1/chat/completions', 'method': 'POST', 'headers': {'host': '0.0.0.0:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '156'}, 'body': {'model': 'gpt4-32K', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}]}}, 'metadata': {'user_api_key': None, 'headers': {'host': '0.0.0.0:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '156'}}, 'request_timeout': 600}
litellm-api  | LiteLLM.Router: Inside async function with retries: args - (); kwargs - {'proxy_server_request': {'url': 'http://0.0.0.0:8000/v1/chat/completions', 'method': 'POST', 'headers': {'host': '0.0.0.0:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '156'}, 'body': {'model': 'gpt4-32K', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}]}}, 'metadata': {'user_api_key': None, 'headers': {'host': '0.0.0.0:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '156'}, 'model_group': 'gpt4-32K'}, 'request_timeout': 600, 'model': 'gpt4-32K', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}], 'original_function': <bound method Router._acompletion of <litellm.router.Router object at 0x7f1c3abdf950>>, 'num_retries': 3}
litellm-api  | LiteLLM.Router: async function w/ retries: original_function - <bound method Router._acompletion of <litellm.router.Router object at 0x7f1c3abdf950>>
litellm-api  | LiteLLM.Router: Inside _acompletion()- model: gpt4-32K; kwargs: {'proxy_server_request': {'url': 'http://0.0.0.0:8000/v1/chat/completions', 'method': 'POST', 'headers': {'host': '0.0.0.0:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '156'}, 'body': {'model': 'gpt4-32K', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}]}}, 'metadata': {'user_api_key': None, 'headers': {'host': '0.0.0.0:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '156'}, 'model_group': 'gpt4-32K'}, 'request_timeout': 600}
litellm-api  | LiteLLM.Router: initial list of deployments: [{'model_name': 'gpt4-32K', 'litellm_params': {'model': 'openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096', 'api_key': 'nothing', 'api_base': 'http://10.11.1.17:5000', 'max_tokens': 4096}, 'model_info': {'id': '822e69a1-0a91-4982-8252-af88ef1572b8'}, 'async_client': <openai.AsyncOpenAI object at 0x7f1c38fe8a10>, 'client': <openai.OpenAI object at 0x7f1c39c00ed0>, 'stream_async_client': <openai.AsyncOpenAI object at 0x7f1c38e85810>, 'stream_client': <openai.OpenAI object at 0x7f1c38ea73d0>}]
litellm-api  | get cache: cache key: 08-58:cooldown_models
litellm-api  | get cache: cache result: None
litellm-api  | LiteLLM.Router: retrieve cooldown models: []
litellm-api  | LiteLLM.Router: cooldown deployments: []
litellm-api  | LiteLLM.Router: healthy deployments: length 1 [{'model_name': 'gpt4-32K', 'litellm_params': {'model': 'openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096', 'api_key': 'nothing', 'api_base': 'http://10.11.1.17:5000', 'max_tokens': 4096}, 'model_info': {'id': '822e69a1-0a91-4982-8252-af88ef1572b8'}, 'async_client': <openai.AsyncOpenAI object at 0x7f1c38fe8a10>, 'client': <openai.OpenAI object at 0x7f1c39c00ed0>, 'stream_async_client': <openai.AsyncOpenAI object at 0x7f1c38e85810>, 'stream_client': <openai.OpenAI object at 0x7f1c38ea73d0>}]
litellm-api  | callback: <bound method Router.deployment_callback of <litellm.router.Router object at 0x7f1c3abdf950>>
litellm-api  | callback: <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7f1c3abdf950>>
litellm-api  | litellm.cache: None
litellm-api  | kwargs[caching]: False; litellm.cache: None
litellm-api  | kwargs[caching]: False; litellm.cache: None
litellm-api  | 
litellm-api  | LiteLLM completion() model= gpt-3.5-turbo; provider = openai
litellm-api  | 
litellm-api  | LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stop': None, 'max_tokens': 4096, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'model': 'gpt-3.5-turbo', 'custom_llm_provider': 'openai', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': 0}
litellm-api  | 
litellm-api  | LiteLLM: Non-Default params passed to completion() {'max_tokens': 4096, 'max_retries': 0}
litellm-api  | self.optional_params: {'max_tokens': 4096, 'max_retries': 0}
litellm-api  | PRE-API-CALL ADDITIONAL ARGS: {'headers': None, 'api_base': 'http://10.11.1.17:5000', 'acompletion': True, 'complete_input_dict': {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}], 'max_tokens': 4096}}
litellm-api  | [92m
litellm-api  | 
litellm-api  | POST Request Sent from LiteLLM:
litellm-api  | curl -X POST \
litellm-api  | http://10.11.1.17:5000 \
litellm-api  | -d '{'model': 'gpt-3.5-turbo', 'messages': [{'role': 'user', 'content': 'where is phousy mountain?'}], 'max_tokens': 4096}'
litellm-api  | [0m
litellm-api  | 
litellm-api  | Logging Details: logger_fn - None | callable(logger_fn) - False
litellm-api  | Logging Details LiteLLM-Failure Call
litellm-api  | LiteLLM.Router: Attempting to add openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096 to cooldown list. updated_fails: 1; self.allowed_fails: 0
litellm-api  | get cache: cache key: 08-58:cooldown_models
litellm-api  | get cache: cache result: None
litellm-api  | LiteLLM.Router: adding openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096 to cooldown models
litellm-api  | set cache: key: 08-58:cooldown_models; value: ['openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096']
litellm-api  | LiteLLM.Router: 
litellm-api  | EXCEPTION FOR DEPLOYMENTS
litellm-api  | 
litellm-api  | LiteLLM.Router: {'openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096': ["<class 'litellm.exceptions.APIError'>Status: 500Message: NoneOpenAIException - cannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.11/site-packages/anyio/_core/_exceptions.py)Full exceptionOpenAIException - cannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.11/site-packages/anyio/_core/_exceptions.py)"]}
litellm-api  | LiteLLM.Router: Model openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096 had 1 exception
litellm-api  | Custom Logger - final response object: None
litellm-api  | LiteLLM.Router: An exception occurs: OpenAIException - cannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.11/site-packages/anyio/_core/_exceptions.py)
litellm-api  | LiteLLM.Router: Trying to fallback b/w models
litellm-api  | [1;31mAn error occurred: OpenAIException - cannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.11/site-packages/anyio/_core/_exceptions.py)
litellm-api  | 
litellm-api  |  Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
litellm-api  | Results from router
litellm-api  | 
litellm-api  | Router stats
litellm-api  | 
litellm-api  | Total Calls made
litellm-api  | openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096: 1
litellm-api  | 
litellm-api  | Success Calls made
litellm-api  | 
litellm-api  | Fail Calls made
litellm-api  | openai/gpt-3.5-turbo-ModelID-openai/gpt-3.5-turbohttp://10.11.1.17:50004096: 1
litellm-api  | INFO:     172.29.0.1:60164 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

**Comment by ghost** [comment]
Hey @chymian i don't think i've ever seen this issue before. Looks like it's being raised by the openai client. 

Does it work when you use the openai client directly? https://github.com/openai/openai-python

**Comment by ghost** [comment]
i just hit this error 

```
iteLLM.Router: {'azure/chatgpt-v-2': ["<class 'ImportError'>Status: Message: NoneFull exceptioncannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.9/site-packages/anyio/_core/_exceptions.py)"]}
LiteLLM.Router: Model azure/chatgpt-v-2 had 1 exception
Custom Logger - final response object: None
LiteLLM.Router: An exception occurs: cannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.9/site-packages/anyio/_core/_exceptions.py)

 TracebackTraceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5149, in exception_type
    request=original_exception.request
AttributeError: 'ImportError' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 385, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 467, in async_function_with_retries
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 447, in async_function_with_retries
    response = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 261, in _acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 255, in _acompletion
    response = await litellm.acompletion(**{**data, "messages": messages, "caching": self.cache_responses, "client": model_client, **kwargs})
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1792, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1723, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 202, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5194, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 192, in acompletion
    response = await init_response
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/azure.py", line 257, in acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/azure.py", line 251, in acompletion
    response = await azure_client.chat.completions.create(**data)
  File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1211, in create
    return await self._post(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1536, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1315, in request
    return await self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1358, in _request
    return await self._retry_request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1416, in _retry_request
    await anyio.sleep(timeout)
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 86, in sleep
    Pause the current task until it's cancelled.
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 161, in get_async_backend
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 61, in <module>
    from .._core._exceptions import ExceptionGroup as BaseExceptionGroup
ImportError: cannot import name 'ExceptionGroup' from 'anyio._core._exceptions' (/usr/local/lib/python3.9/site-packages/anyio/_core/_exceptions.py)

LiteLLM.Router: Trying to fallback b/w models
INFO:     172.17.0.1:45752 - "POST /queue/chat/completions HTTP/1.1" 400 Bad Request
```

**Comment by ghost** [comment]
Looks like it was an error related to the anyio version (openai accepts any > 3.5 but even 3.7.1 was raising this error). I managed to fix this by updating my anyio version to 4.2.1 

Going to version lock this on the dockerfile too.

**Comment by ghost** [comment]
Fixed with new requirements.txt which pins the anyio version. @chymian please re-open if the issue persists.

**Comment by chymian** [comment]
@krrishdholakia 
I can confirm it's working with 1.15.1, even so anyio is at 3.7.1
```bash
anyio              3.7.1
fastapi            0.104.1
litellm            1.15.1
openai             1.5.0
```

### this might be OT:
in the config for WEBUI:  `api_base: http://10.11.1.17:5000/v1`
must have the `/v1`, then both variations work.

-  `curl http://0.0.0.0:8000/v1/chat/completions`
 - `curl http://0.0.0.0:8000/chat/completions`

on the other hand,  if `/v1` is not in the `api_base` , an exeption error  `Detail not found` is raised  on both:

-  `curl http://0.0.0.0:8000/v1/chat/completions`
-  `curl http://0.0.0.0:8000/chat/completions`
 
 is that the inteded behavior?
