### PR TITLE
fix(openrouter): move usage accounting to extra_body for compatibility

### PR DESCRIPTION
**Pull request by looksgood**
## Relevant issues

Fixes the OpenRouter request assembly bug where every chat request was given a top-level `usage` field, which OpenAI-compatible clients reject with `AsyncCompletions.create() got an unexpected keyword argument 'usage'` (hit when calling OpenAI-backed models through OpenRouter)

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added meaningful tests
- [x] My PR passes all unit tests on [`make test-unit`](https://docs.litellm.ai/docs/extras/contributing_code)
- [x] My PR's scope is as isolated as possible; it only solves 1 specific problem
- [ ] I have requested a Greptile review by commenting `@greptileai` and received a **Confidence Score of at least 4/5** before requesting a maintainer review

## Delays in PR merge?

If you're seeing a delay in your PR being merged, ping the LiteLLM Team on [Slack (#pr-review)](https://join.slack.com/t/litellmossslack/shared_invite/zt-3o7nkuyfr-p_kbNJj8taRfXGgQI1~YyA).

## CI (LiteLLM team)

> **CI status guideline:**
>
> - 50-55 passing tests: main is stable with minor issues.
> - 45-49 passing tests: acceptable but needs attention
> - <= 40 passing tests: unstable; be careful with your merges and assess the risk.

- [ ] **Branch creation CI run**  
       Link:

- [ ] **CI run for the last commit**  
       Link:

- [ ] **Merge / cherry-pick CI run**  
       Links:

## Screenshots / Proof of Fix

The failure shows up via the admin UI "Test Connection" button when adding an OpenRouter model. That button calls `/health/test_connection` -> `ahealth_check` -> `acompletion`, which sends the probe request through the OpenAI SDK's `chat.completions.create()`. LiteLLM injects a top-level `usage: {include: true}` on OpenRouter requests for cost tracking, and when the request goes through the OpenAI SDK that `usage` is passed as a keyword argument, which the SDK rejects.

Reproduced against the live OpenRouter API with the OpenAI SDK.

Before (top-level `usage`, what the old code produced):

```python
from openai import OpenAI

client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key="<OPENROUTER_KEY>")
client.chat.completions.create(
    model="openai/gpt-5.5",
    messages=[{"role": "user", "content": "Hey how's it going?"}],
    usage={"include": True},
)
# TypeError: Completions.create() got an unexpected keyword argument 'usage'
# (async path reports AsyncCompletions.create(), same root cause)
```

After (`usage` inside `extra_body`, what this PR produces):

```python
client.chat.completions.create(
    model="openai/gpt-5.5",
    messages=[{"role": "user", "content": "Hey how's it going? reply in one short sentence"}],
    extra_body={"usage": {"include": True}},
)
# 200 OK -> "Going great, hope you're doing well too!"
# OpenRouter still returns cost: usage.cost = 0.000505, so cost tracking keeps working
```

The normal `litellm.completion` path is unaffected because it sends OpenRouter requests over raw httpx, where a top-level `usage` is just a JSON field; the regression only hit paths that route through the OpenAI SDK (the connection test / health check). The regression test was reworked in 88840fff54 to drive the full completion path and assert on the request body actually posted.

## Type

🐛 Bug Fix

### CODE REVIEW

File: litellm/llms/openrouter/chat/transformation.py [hunk 1]
```diff
@@ -167,17 +167,19 @@ def transform_request(
...
-        # ALWAYS add usage parameter to get cost data from OpenRouter
-        # This ensures cost tracking works for all OpenRouter models
-        if "usage" not in response:
-            response["usage"] = {"include": True}
+        # Usage accounting is an OpenRouter-specific flag, not a valid top-level
+        # OpenAI chat param. Sending it at the top level makes OpenAI-compatible
+        # clients reject the request ("unexpected keyword argument 'usage'"), so
+        # it must travel inside `extra_body` instead.
+        extra_body = request.setdefault("extra_body", {})
+        extra_body.setdefault("usage", {"include": True})
```
[the remark this answers is not in the document]
Comment (looksgood) [reply litellm/llms/openrouter/chat/transformation.py:180]: I checked this against the live OpenRouter API and cost tracking works end to end on this branch. For an openrouter/openai/* call, response_cost, usage.cost, and cost_details.upstream_inference_cost all come back populated. I also captured the raw outgoing HTTP body with an httpx hook and, as a direct test of this exact concern, sent a request with usage nested inside extra_body; OpenRouter still returned the cost data. The silent-failure scenario does not reproduce, so I'm treating this as a false positive

File: tests/test_litellm/llms/openrouter/chat/test_openrouter_chat_transformation.py [hunk 2]
```diff
@@ -528,6 +526,43 @@ def test_openrouter_cost_tracking_streaming():
...
+        litellm_params={},
+        headers={},
+    )
+
+    assert "usage" not in transformed_request
+    assert transformed_request["provider"]["order"] == ["OpenAI"]
+    assert transformed_request["extra_body"]["usage"] == {"include": True}
+
+
 def test_openrouter_reasoning_models_allow_reasoning_effort_param():
```
[the remark this answers is not in the document]
Comment (looksgood) [reply tests/test_litellm/llms/openrouter/chat/test_openrouter_chat_transformation.py:610]: Good catch, this is fair. extra_body is popped from optional_params in llm_http_handler before transform_request runs, so the merge that lifts a user-provided param like provider to the top level happens in the handler, and the old direct-call test exercised a path production never takes. I reworked the test in 88840fff54 to drive the full completion path with a mocked client and assert on the request body actually posted: the user-provided OpenRouter param lands at the top level and usage accounting reaches the shipped body. It fails if either the usage accounting or the handler merge is removed

**Comment by Sameerlite** [comment]
Thanks for the PR! A couple of things to get this over the finish line:
- Could you add proof of the change working (screenshots, test output, or a sample request/response)? Even a quick `curl` before/after really speeds up the review.

Triggering Greptile for a code review in the meantime:

@greptileai

**Comment by looksgood** [comment]
> Thanks for the PR! A couple of things to get this over the finish line:
> 
> * Could you add proof of the change working (screenshots, test output, or a sample request/response)? Even a quick `curl` before/after really speeds up the review.
> 
> Triggering Greptile for a code review in the meantime:
> 
> @greptileai

Repro is the "Test Connection" button when adding an OpenRouter model in the admin UI (it runs /health/test_connection -> ahealth_check -> acompletion, which sends the request through the OpenAI SDK's chat.completions.create()).

LiteLLM injects a top-level usage: {include: true} on OpenRouter requests for cost tracking. When that request goes through the OpenAI SDK, usage is passed as a keyword argument and the SDK rejects it:

  BEFORE: client.chat.completions.create(model="openai/gpt-5.5", messages=[...], usage={"include": True})
       -> TypeError: Completions.create() got an unexpected keyword argument 'usage'

This PR moves the flag into extra_body, which the OpenAI SDK supports and forwards in the request body:

  AFTER:  client.chat.completions.create(model="openai/gpt-5.5", messages=[...], extra_body={"usage": {"include": True}})
       -> 200 OK, and OpenRouter returns cost (usage.cost=0.000505), so cost tracking still works

Both run against the live OpenRouter API. I also reworked the regression test in 88840fff54 to drive the full completion path and assert on the body actually posted.

**Comment by Sameerlite** [comment]
Thanks for the contribution! A couple of things to get this over the finish line:

- Greptile gave this a 4/5 confidence score — there may be some open feedback to address in the review comments before we can merge.

Once those are addressed, we'll take another look!
