### PR TITLE
Fix Anthropic streaming web search cost usage

### LINKED ISSUE #26153: [Bug]: `completion_cost()` raises `AttributeError` on streaming Anthropic responses with web_search in v1.83.10
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

In v1.83.10, `completion_cost()` raises `AttributeError: 'dict' object has no attribute 'web_search_requests'` when called on a streaming Anthropic response that used `web_search_options`.

The root cause: `stream_chunk_builder` reconstructs `usage.server_tool_use` as a `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check was added in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` that accesses `usage.server_tool_use.web_search_requests` directly (see [`tool_call_cost_tracking.py#L340-L344`](https://github.com/BerriAI/litellm/blob/v1.83.10/litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py#L340-L344)). The same pattern also exists in `get_cost_for_anthropic_web_search` in `anthropic/cost_calculation.py#L131`.

This was working in 1.83.0 because the new `server_tool_use` branch in the guard didn't exist, so `_handle_web_search_cost()` was never reached for streaming Anthropic responses.

### Suggested fix

Either:

1. Coerce `server_tool_use` to `ServerToolUse` in `stream_chunk_builder` when reconstructing usage from streaming chunks (addresses root cause), or
2. Use `getattr(..., 'web_search_requests', None)` or `nested_idx`-style dict/attr tolerant access in the two call sites above.

### Version

litellm==1.83.10 (works in 1.83.0)
Python 3.12

### Steps to Reproduce

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role':'user','content':'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size':'low'},
    stream_options={'include_usage':True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # <class 'dict'>
completion_cost(completion_response=r)  # AttributeError
```

### Expected

`completion_cost()` returns a float (as in 1.83.0).

### Relevant log output

```shell
File .../litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py:343, in response_object_includes_web_search_call
    and usage.server_tool_use.web_search_requests is not None
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

### What part of LiteLLM is this about?

SDK (litellm Python package)

### What LiteLLM version are you on ?

1.83.10

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by oss-agent-shin**
## Summary
Fixes #26153. `stream_chunk_builder()` was rehydrating Anthropic `usage.server_tool_use` as a plain dict, so `completion_cost()` crashed when web-search cost tracking accessed `web_search_requests` as an attribute. This coerces `server_tool_use` back to `ServerToolUse` during usage reconstruction and when dict snapshot chunks are processed.

## Repro
On the starting ref, run:

```bash
~/.local/bin/uv run pytest tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py::test_stream_chunk_builder_anthropic_web_search_completion_cost -q
```

The added regression fails before the fix with:

```text
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

## Evidence
Could not host screenshot evidence as a gist because `$SHIN_GITHUB_TOKEN` lacks the required `gist` scope (`gh gist create` returned: `This API operation needs the "gist" scope`). Terminal transcript fallback:

```text
$ ~/.local/bin/uv run pytest tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py::test_stream_chunk_builder_anthropic_web_search_completion_cost tests/test_litellm/litellm_core_utils/llm_cost_calc/test_tool_call_cost_tracking.py -q
...............                                                          [100%]
15 passed in 0.22s
```

## Tests
- `~/.local/bin/uv run pytest tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py tests/test_litellm/litellm_core_utils/llm_cost_calc/test_tool_call_cost_tracking.py -q` -> 24 passed
- `~/.local/bin/uv run pytest tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py::test_stream_chunk_builder_anthropic_web_search_completion_cost tests/test_litellm/litellm_core_utils/llm_cost_calc/test_tool_call_cost_tracking.py -q` -> 15 passed
- `~/.local/bin/uv run ruff check --select F401,F821 litellm/types/utils.py litellm/litellm_core_utils/streaming_chunk_builder_utils.py tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py` -> passed
- `PATH="$HOME/.local/bin:$PATH" make test-unit` -> failed due unrelated environment/existing failures: invalid OpenAI API key in OpenAI-dependent tests and `/get/config/callbacks` test setup missing a temp config file.

## Relevant issues

Fixes #26153

## Linear ticket

N/A

## Pre-Submission checklist

- [x] I have Added testing in the [`tests/test_litellm/`](https://github.com/BerriAI/litellm/tree/main/tests/test_litellm) directory, **Adding at least 1 test is a hard requirement** - [see details](https://docs.litellm.ai/docs/extras/contributing_code)
- [ ] My PR passes all unit tests on [`make test-unit`](https://docs.litellm.ai/docs/extras/contributing_code)
- [x] My PR's scope is as isolated as possible, it only solves 1 specific problem
- [ ] I have requested a Greptile review by commenting `@greptileai` and received a **Confidence Score of at least 4/5** before requesting a maintainer review

## Screenshots / Proof of Fix

```text
$ ~/.local/bin/uv run pytest tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py::test_stream_chunk_builder_anthropic_web_search_completion_cost tests/test_litellm/litellm_core_utils/llm_cost_calc/test_tool_call_cost_tracking.py -q
...............                                                          [100%]
15 passed in 0.22s
```

## Type

🐛 Bug Fix
✅ Test

## Changes

- Preserve `ServerToolUse` for `Usage(server_tool_use=...)` when rehydrating from dicts.
- Coerce `server_tool_use` while aggregating usage from streaming dict snapshots.
- Add regression coverage proving Anthropic streaming web-search usage no longer crashes `completion_cost()`.

### CODE REVIEW

**Comment by oss-agent-shin** [comment]
Closing — bulk cleanup of PRs filed by this account.
