### ISSUE TITLE
[Bug]: ImportError: cannot import name 'T' from 're' #7311

### ISSUE THREAD

**Issue by Rishang** [BerriAI/litellm#7323]
### What happened?

#7311 this issue is still present

litellm                      1.55.7
python                     3.13

It is working in version `litellm-1.55.3` for later versions this issue is present.
### Relevant log output

```shell
logs are mention here: #7311
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.55.7

**Comment by ghost** [comment]
Closing as the fix is on main but working through ci/cd. will be live on v1.55.8. Response with more details on previous ticket. if necessary, we can reopen that one.
