### ISSUE TITLE
[Bug]: /{provider}/v1/files shadows the /anthropic passthrough → 422 "purpose Field required"

### ISSUE THREAD

**Issue by andrewli-gyde** [BerriAI/litellm#37289]
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

Same shadowing as #36086, on a different prefix. #36092 fixed `/openai_passthrough` and states
"other provider prefixes keep today's behavior" — `/anthropic` is still affected on `main`.

- `POST /anthropic/v1/files` is answered by LiteLLM's OpenAI files endpoint instead of being
  forwarded, and fails `422 {"loc":["body","purpose"],"msg":"Field required"}`
- `purpose` is OpenAI-only. Anthropic's Files API has no such field, so the Anthropic SDK never
  sends one — `client.beta.files.upload({ file })` has no `purpose` param. The request cannot succeed
- Adding `purpose` doesn't help: that path 500s on `files_settings is not set`
- Regressed in v1.92.0 via [#30958](https://github.com/BerriAI/litellm/pull/30958/files#diff-cb47ff448a23857ca19cd50f8baa9aea47ee5cdefb475803fdc022449dc10d7eR15624),
  which moved `batches_router` and `openai_files_router` above the passthrough routers in
  `proxy_server.py`. Worked on v1.83.14-stable, where the order was reversed
- `POST /anthropic/v1/files/` (trailing slash) is forwarded correctly, so it's route precedence,
  not the body

Expected: `/anthropic/v1/files` forwards to `api.anthropic.com/v1/files` like every other path
under `/anthropic/`.

### User Flow

Before: a developer using the Anthropic SDK against the gateway cannot upload a document at all, so
the model never sees their PDF.

1. They set base URL `https://litellm-domain/anthropic` and send
   `POST https://litellm-domain/anthropic/v1/files` with `file=@plan.pdf` — what
   `client.beta.files.upload({ file })` emits
2. They get `422 {"detail":[{"type":"missing","loc":["body","purpose"],"msg":"Field required"}]}`,
   no file id, and nothing in their Anthropic account
3. They add `purpose=user_data` and retry the same POST
4. They get `500 {"error":{"message":"files_settings is not set, set it on your config.yaml file."}}`
5. With no file id they cannot reference the document in
   `POST https://litellm-domain/anthropic/v1/messages`, so the answer ignores their PDF

After: the same upload returns an Anthropic file id and the model reads the document.

1. They set base URL `https://litellm-domain/anthropic` and send the same
   `POST https://litellm-domain/anthropic/v1/files` with `file=@plan.pdf`, no extra fields
2. They get `200` with Anthropic's own file object —
   `{"type":"file","id":"file_011Ce8...","mime_type":"application/pdf"}` — visible in their account
3. They send `POST https://litellm-domain/anthropic/v1/messages` with a `document` block using that
   `file_id`
4. They get `200` and the reply quotes the PDF's contents

### Proof the bug occurs

`config.yaml`:

```yaml
model_list:
  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/claude-haiku-4-5
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  master_key: sk-local-repro-master
```

Env: `ANTHROPIC_API_KEY=sk-ant-invalid-key-for-local-repro`, `CONFIG_FILE_PATH=./config.yaml`,
`LITELLM_MASTER_KEY=sk-local-repro-master`

Version: `litellm==1.96.2`, run as
`python -m uvicorn litellm.proxy.proxy_server:app --host 127.0.0.1 --port 4000`

The Anthropic key is invalid on purpose — it makes routing unambiguous for free. A request LiteLLM
answers itself fails 422 on `purpose`; a request that is forwarded fails 401 at Anthropic.

1. What the SDK sends — intercepted, never forwarded:

```
$ curl -s -w "\nHTTP %{http_code}\n" -X POST http://127.0.0.1:4000/anthropic/v1/files \
    -H "x-api-key: $MASTER_KEY" -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: files-api-2025-04-14" -F "file=@repro.pdf;type=application/pdf"

{"detail":[{"type":"missing","loc":["body","purpose"],"msg":"Field required","input":null}]}
HTTP 422
```

2. Trailing slash — forwarded, 401 from Anthropic as expected with an invalid key:

```
$ curl -s -w "\nHTTP %{http_code}\n" -X POST http://127.0.0.1:4000/anthropic/v1/files/ \
    -H "x-api-key: $MASTER_KEY" -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: files-api-2025-04-14" -F "file=@repro.pdf;type=application/pdf"

{"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}
HTTP 401
```

3. Control — `/anthropic/v1/messages` forwards normally, same 401:

```
$ curl -s -X POST http://127.0.0.1:4000/anthropic/v1/messages \
    -H "x-api-key: $MASTER_KEY" -H "anthropic-version: 2023-06-01" \
    -H "content-type: application/json" \
    -d '{"model":"claude-haiku-4-5","max_tokens":16,"messages":[{"role":"user","content":"hi"}]}'

{"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}
HTTP 401
```

2 and 3 prove the passthrough is wired correctly; 1 differs only in path shape.

4. With a valid Anthropic key on a v1.96.2 gateway (key and host redacted), the trailing-slash path
completes the round trip:

```
POST /anthropic/v1/files/?beta=true
{"type":"file","id":"file_011CeAPEhuywu41e5rH8h3Dp","size_bytes":401,
 "created_at":"2026-08-18T14:37:54.596000Z","filename":"repro.pdf",
 "mime_type":"application/pdf","downloadable":false}
HTTP 200

POST /anthropic/v1/messages   (document block referencing that file_id)
{"content":[{"type":"text","text":"passthrough round trip ok"}],"stop_reason":"end_turn"}
```

"passthrough round trip ok" is the literal text in the uploaded PDF, so the model read the document.

# Suggested fix

- give `/anthropic` its own router mounted ahead of batches and files, as #36092 did for
  `/openai_passthrough`
- or scope `/{provider}/v1/files` so it cannot shadow a registered passthrough prefix, which covers
  every provider whose native API has no `purpose`

### What part of LiteLLM is this about?

Proxy

### What LiteLLM version are you on ?

v1.96.2

**Comment by nightcityblade** [comment]
Update: I cannot submit against the required base branch, so I am withdrawing my claim. This issue remains available.

**Comment by IdoPort** [comment]
I am also having trouble with that case would appreciate the help of getting it resolved
