### PR TITLE
fix: completion_cost AttributeError on streaming Anthropic web_search responses (#26153)

### LINKED ISSUE #26153: [Bug]: `completion_cost()` raises `AttributeError` on streaming Anthropic responses with web_search in v1.83.10
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

In v1.83.10, `completion_cost()` raises `AttributeError: 'dict' object has no attribute 'web_search_requests'` when called on a streaming Anthropic response that used `web_search_options`.

The root cause: `stream_chunk_builder` reconstructs `usage.server_tool_use` as a `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check was added in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` that accesses `usage.server_tool_use.web_search_requests` directly (see [`tool_call_cost_tracking.py#L340-L344`](https://github.com/BerriAI/litellm/blob/v1.83.10/litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py#L340-L344)). The same pattern also exists in `get_cost_for_anthropic_web_search` in `anthropic/cost_calculation.py#L131`.

This was working in 1.83.0 because the new `server_tool_use` branch in the guard didn't exist, so `_handle_web_search_cost()` was never reached for streaming Anthropic responses.

### Suggested fix

Either:

1. Coerce `server_tool_use` to `ServerToolUse` in `stream_chunk_builder` when reconstructing usage from streaming chunks (addresses root cause), or
2. Use `getattr(..., 'web_search_requests', None)` or `nested_idx`-style dict/attr tolerant access in the two call sites above.

### Version

litellm==1.83.10 (works in 1.83.0)
Python 3.12

### Steps to Reproduce

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role':'user','content':'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size':'low'},
    stream_options={'include_usage':True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # <class 'dict'>
completion_cost(completion_response=r)  # AttributeError
```

### Expected

`completion_cost()` returns a float (as in 1.83.0).

### Relevant log output

```shell
File .../litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py:343, in response_object_includes_web_search_call
    and usage.server_tool_use.web_search_requests is not None
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

### What part of LiteLLM is this about?

SDK (litellm Python package)

### What LiteLLM version are you on ?

1.83.10

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by ishaan-berri**
## Relevant issues

Fixes #26153

## Linear ticket

(no Linear ticket — bug fix from external user)

## Pre-Submission checklist

- [x] I have added testing in tests/test_litellm/ — 3 new test files, 18 new tests
- [x] My PR passes all unit tests on `make test-unit`
- [x] My PR's scope is as isolated as possible — fixes one specific bug
- [ ] I have requested a Greptile review by commenting `@greptileai`

## CI (LiteLLM team)

- [ ] Branch creation CI run — link:
- [ ] CI run for the last commit — link:
- [ ] Merge / cherry-pick CI run — links:

## Screenshots / Proof of Fix

Before:
```python
>>> r = stream_chunk_builder(chunks)
>>> completion_cost(completion_response=r)
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

After:
```python
>>> r = stream_chunk_builder(chunks)
>>> type(r.usage.server_tool_use)
<class 'litellm.types.utils.ServerToolUse'>
>>> completion_cost(completion_response=r)
0.00347  # works
```

## Type

Bug Fix

## Changes

Two-pronged fix per the issuer's recommendation:

1. **Root cause:** `Usage.__init__` and `stream_chunk_builder` now coerce `server_tool_use` to `ServerToolUse` pydantic when reconstructing `usage` from streaming chunks. Previously the streaming path round-tripped through `model_dump()` and re-built `Usage(**dump)` which left `server_tool_use` as a plain dict.
2. **Defensive at call sites:** added `_get_web_search_requests` helper that handles None / dict / ServerToolUse uniformly. Used in `tool_call_cost_tracking.py` and `anthropic/cost_calculation.py`.

Both fixes shipped together. Tests cover the regression + the helper's tolerance for all input types.

### CODE REVIEW

**Comment by DmitriyAlergant** [comment]
@ishaan-berri this fixes the prior regression (spend calculation no longer fails), but the cost of Anthropic Web Search is still not included into the total spend

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
@greptileai

**Comment by mateo-berri** [comment]
@greptileai

**Review by mateo-berri — APPROVED** [review]
LGTM; thanks!
