### ISSUE TITLE
[Bug]: Can't import library on Python 3.8

### ISSUE THREAD

**Issue by davidmezzetti** [BerriAI/litellm#2005]
### What happened?

Can't import library on Python 3.8 with latest version (v1.24.3)

Works with v1.23.16

### Relevant log output

```shell
>>> import litellm
Traceback (most recent call last):
  File "litellm/utils.py", line 41, in <module>
    resources.files().joinpath("llms/tokenizers")  # type: ignore
AttributeError: module 'importlib.resources' has no attribute 'files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "litellm/__init__.py", line 524, in <module>
    from .utils import (
  File "litellm/utils.py", line 45, in <module>
    resources.files(litellm).joinpath("llms/tokenizers")  # for python 3.10
AttributeError: module 'importlib.resources' has no attribute 'files'
```

**Comment by ghost** [comment]
cc: @sorokine?

**Comment by davidmezzetti** [comment]
https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files

_New in version 3.9._

[This issue ](https://github.com/mu-editor/pup/issues/35)looks like they solved it by requiring `importlib_resources` for 3.8

**Comment by ghost** [comment]
is this now fixed in v`1.25.2`? @davidmezzetti

**Comment by davidmezzetti** [comment]
Working now, thank you!
