### ISSUE TITLE
[Bug]: /v1/batches - 401 Unauthorized - When Metadata is null

### ISSUE THREAD

**Issue by mishaja12** [BerriAI/litellm#17263]
### What happened?

Send a request to /v1/batches with OpenAi request and set Metadata as `null`. Version 1.80.0-stable has this issue after updating from 1.77.3

litellm.proxy.proxy_server.user_api_key_auth(): Exception occured - 'NoneType'
401 Unauthorized 

### Relevant log output

```shell
{"message": "litellm.proxy.proxy_server.user_api_key_auth(): Exception occured - 'NoneType' object has no attribute 'get'\nRequester IP Address:10.42.58.36", "level": "ERROR", "timestamp": "2025-11-28T16:18:15.483661", "stacktrace": "Traceback (most recent call last):\n  File \"/app/litellm/proxy/auth/user_api_key_auth.py\", line 1122, in _user_api_key_auth_builder\n    _ = await common_checks(\n        ^^^^^^^^^^^^^^^^^^^^\n    ...<11 lines>...\n    )\n    ^\n  File \"/app/litellm/proxy/auth/auth_checks.py\", line 146, in common_checks\n    await _tag_max_budget_check(\n    ...<5 lines>...\n    )\n  File \"/app/litellm/proxy/auth/auth_checks.py\", line 1941, in _tag_max_budget_check\n    tags = get_tags_from_request_body(request_body=request_body)\n  File \"/app/litellm/proxy/common_utils/http_parsing_utils.py\", line 266, in get_tags_from_request_body\n    tags_in_metadata: Any = metadata.get(\"tags\", [])\n                            ^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'get'"}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.80.0
