### PR TITLE
Fix Anthropic streaming web search cost usage

### LINKED ISSUE #26153: [Bug]: `completion_cost()` raises `AttributeError` on streaming Anthropic responses with web_search in v1.83.10
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

In v1.83.10, `completion_cost()` raises `AttributeError: 'dict' object has no attribute 'web_search_requests'` when called on a streaming Anthropic response that used `web_search_options`.

The root cause: `stream_chunk_builder` reconstructs `usage.server_tool_use` as a `dict` rather than a `ServerToolUse` pydantic object. In v1.83.10, a new check was added in `StandardBuiltInToolCostTracking.response_object_includes_web_search_call` that accesses `usage.server_tool_use.web_search_requests` directly (see [`tool_call_cost_tracking.py#L340-L344`](https://github.com/BerriAI/litellm/blob/v1.83.10/litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py#L340-L344)). The same pattern also exists in `get_cost_for_anthropic_web_search` in `anthropic/cost_calculation.py#L131`.

This was working in 1.83.0 because the new `server_tool_use` branch in the guard didn't exist, so `_handle_web_search_cost()` was never reached for streaming Anthropic responses.

### Suggested fix

Either:

1. Coerce `server_tool_use` to `ServerToolUse` in `stream_chunk_builder` when reconstructing usage from streaming chunks (addresses root cause), or
2. Use `getattr(..., 'web_search_requests', None)` or `nested_idx`-style dict/attr tolerant access in the two call sites above.

### Version

litellm==1.83.10 (works in 1.83.0)
Python 3.12

### Steps to Reproduce

```python
from litellm import completion, stream_chunk_builder, completion_cost

chunks = list(completion(
    'claude-sonnet-4-6',
    [{'role':'user','content':'Search the web for otters and tell me one fact'}],
    stream=True,
    web_search_options={'search_context_size':'low'},
    stream_options={'include_usage':True},
))
r = stream_chunk_builder(chunks)
print(type(r.usage.server_tool_use))  # <class 'dict'>
completion_cost(completion_response=r)  # AttributeError
```

### Expected

`completion_cost()` returns a float (as in 1.83.0).

### Relevant log output

```shell
File .../litellm/litellm_core_utils/llm_cost_calc/tool_call_cost_tracking.py:343, in response_object_includes_web_search_call
    and usage.server_tool_use.web_search_requests is not None
AttributeError: 'dict' object has no attribute 'web_search_requests'
```

### What part of LiteLLM is this about?

SDK (litellm Python package)

### What LiteLLM version are you on ?

1.83.10

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by oss-agent-shin**
## Summary
`Usage` now normalizes dict-shaped `server_tool_use` payloads back into `ServerToolUse` objects. This preserves typed usage after streaming responses are rebuilt and prevents web-search cost calculation from raising on Anthropic streaming responses.

## Repro
A streaming Anthropic chat completion with web search usage emits chunks whose aggregated usage is round-tripped through `model_dump()`. Before this fix, the rebuilt response had `usage.server_tool_use` as a dict, and calling cost calculation on the response raised an attribute error.

## Evidence
Terminal transcript from the local repro after the fix:

```text
ServerToolUse
2
0.020555
```

## Tests
- Added regression coverage in `tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py` for streaming Anthropic web-search cost calculation.
- Added round-trip coverage in `tests/test_litellm/types/test_types_utils.py` for `Usage(**usage.model_dump())` preserving `ServerToolUse`.
- `uv run --no-sync pytest tests/test_litellm/types/test_types_utils.py tests/test_litellm/litellm_core_utils/test_streaming_chunk_builder_utils.py -vv` -> 26 passed.
- `uv lock --check` -> passed.
- `uv sync --frozen` -> passed.
- `cd litellm && uv run --no-sync black --check --exclude '/enterprise/' .` -> passed.
- `cd litellm && uv run --no-sync ruff check .` -> passed.
- `cd litellm && uv run --no-sync mypy .` -> passed.
- `cd litellm && uv run --no-sync python ../tests/documentation_tests/test_circular_imports.py` -> passed.
- `uv run --no-sync python -c "from litellm import *"` -> passed.

## CI
- GitHub PR checks: all visible jobs green, including lint, core-utils, responses-caching-types, provider tests, proxy tests, code-quality, secret scan, and UI build.
- CircleCI: no pipeline was visible for this fork branch through the available public API; GitHub checks were used as the observable PR CI signal.

## Review
- Greptile review: no review was posted after the wait window, so there were no automated review threads to address.

## Relevant issues
Fixes #26153

## Linear ticket

N/A

## Pre-Submission checklist

- [x] I have Added testing in the `tests/test_litellm/` directory, Adding at least 1 test is a hard requirement
- [ ] My PR passes all unit tests on `make test-unit`
- [x] My PR's scope is as isolated as possible, it only solves 1 specific problem
- [ ] I have requested a Greptile review and received a Confidence Score of at least 4/5 before requesting a maintainer review

## Delays in PR merge?

N/A

## CI (LiteLLM team)

- [x] Branch creation CI run
       Link: https://github.com/BerriAI/litellm/actions/runs/25468084127

- [x] CI run for the last commit
       Link: https://github.com/BerriAI/litellm/actions/runs/25468084104

- [ ] Merge / cherry-pick CI run
       Links:

## Screenshots / Proof of Fix

See the terminal transcript in `## Evidence`.

## Type

🐛 Bug Fix
✅ Test

## Changes
- Normalize dict `server_tool_use` inputs in `Usage`.
- Assert streaming Anthropic web-search usage remains typed after aggregation.
- Assert completion cost calculation succeeds for the rebuilt streaming response.

### CODE REVIEW

**Comment by oss-agent-shin** [comment]
Closing — bulk cleanup of PRs filed by this account.
