### ISSUE TITLE
[Bug]: bedrock exception when using 1.38.10

### ISSUE THREAD

**Issue by pharindoko** [BerriAI/litellm#3878]
### What happened?

Hey, 

seems like something broke between versions
1.37.5 and 1.38.11

I do get following trying to use claude v2:1.

```
outer.py:657 - litellm.acompletion(model=None) Exception No deployments available for selected model, Try again in 1 seconds. Passed model=anthropic.claude-v2:1. pre-call-checks=True, allowed_model_region=n/a
```

I have never seen this issue before with version 1.37.5

**Comment by ishaan-jaff** [comment]
@pharindoko this means all your deployments are in cool-down. It's always existed. I'm assuming your endpoints were raising more errors during this time

**Comment by pharindoko** [comment]
> @pharindoko this means all your deployments are in cool-down. It's always existed. I'm assuming your endpoints were raising more errors during this time 

I'll check it again...

**Comment by ghost** [comment]
yea - we're seeing this with users on older versions too - i think the anthropic bedrock endpoints might be unstable today @pharindoko

**Comment by pharindoko** [comment]
Hi, I tested it again and there seems to be something wrong with the security token in auth.py

448: botocore/auth.py
        if self.credentials.token:

this is where it fails

Called by bedrock_httpx.py 
line 783: sigv4.add_auth(request)

Partially the self.credentials.token is set and partially not.

I get this exception
`14:39:24 - LiteLLM Router:INFO: router.py:658 - litellm.acompletion(model=bedrock/anthropic.claude-v2:1) Exception BedrockException - 'dict' object has no attribute 'token'`

**Comment by pharindoko** [comment]
@krrishdholakia @ishaan-jaff 

Yeah the credentials will be overwritten 

in botocore auth.py in SigV4Auth line:217
```
class SigV4Auth(BaseSigner):
    """
    Sign a request with Signature V4.
    """

    REQUIRES_REGION = True

    def __init__(self, credentials, service_name, region_name):
        self.credentials = credentials
        # We initialize these value here so the unit tests can have
        # valid values.  But these will get overriden in ``add_auth``
        # later for real requests.
```
with
```

'AccessKeyId':'xxx'
'SecretAccessKey':'xxxx'
'SessionToken':'xxx
```

expected properties in credentials are:
```
access_key:
'xxxx'
secret_key:
'xxx'
token:
'xxx'
```

**Comment by pharindoko** [comment]
this worked in 1.37.5 as expected

**Comment by pharindoko** [comment]
@ishaan-jaff  @krrishdholakia  can you reopen it and have a look at it ?

**Comment by ghost** [comment]
@pharindoko this works for us, can you please share how you're making the call / setting credentials?

**Comment by ghost** [comment]
<img width="1638" alt="Screenshot 2024-05-29 at 8 57 47 AM" src="https://github.com/BerriAI/litellm/assets/17561003/493c645c-2552-4c84-9e7d-e52f11241ead">

@pharindoko sharing image of successful call for `anthropic.claude-v2:1` on latest litellm


## Code

```python
import os
from litellm import completion

os.environ["AWS_ACCESS_KEY_ID"] = ""
os.environ["AWS_SECRET_ACCESS_KEY"] = ""
os.environ["AWS_REGION_NAME"] = ""

response = completion(
  model="bedrock/anthropic.claude-v2:1",
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)

print("\nResponse:\n{}\n".format(response))
```

**Comment by pharindoko** [comment]
> <img width="1638" alt="Screenshot 2024-05-29 at 8 57 47 AM" src="https://github.com/BerriAI/litellm/assets/17561003/493c645c-2552-4c84-9e7d-e52f11241ead">
> 
> 
> 
> @pharindoko sharing image of successful call for `anthropic.claude-v2:1` on latest litellm
> 
> 
> 
> 
> 
> ## Code
> 
> 
> 
> ```python
> 
> import os
> 
> from litellm import completion
> 
> 
> 
> os.environ["AWS_ACCESS_KEY_ID"] = ""
> 
> os.environ["AWS_SECRET_ACCESS_KEY"] = ""
> 
> os.environ["AWS_REGION_NAME"] = ""
> 
> 
> 
> response = completion(
> 
>   model="bedrock/anthropic.claude-v2:1",
> 
>   messages=[{ "content": "Hello, how are you?","role": "user"}]
> 
> )
> 
> 
> 
> print("\nResponse:\n{}\n".format(response))
> 
> ```

And this works for me too with iam roles. 

I think the special thing is that I assume roles in other accounts to do the routing.

Still tried it out locally and in the cloud an it works with 1.37.5 and fails since 1.38.10.

**Comment by ghost** [comment]
> I think the special thing is that I assume roles in other accounts to do the routing.

can you share what this looks like when making the litellm call? 

> works with 1.37.5 and fails since 1.38.10

This is probably caused by making the bedrock calls via httpx instead of boto3 (boto3 is not async). 

Relevant file: https://github.com/BerriAI/litellm/blob/c76deb8f762455876efde3549f23e9a2740a4719/litellm/llms/bedrock_httpx.py#L4


--- 
we still use boto3 for getting the credentials from the environment - 

this is the relevant file - https://github.com/BerriAI/litellm/blob/c76deb8f762455876efde3549f23e9a2740a4719/litellm/llms/bedrock_httpx.py#L212

let me know what we're missing

**Comment by pharindoko** [comment]
@krrishdholakia  @ishaan-jaff 
Guess i figured it out what\`s the problem.
This works for me locally when assuming a role in a different aws account.
I wasn`t able to adjust the tests accordingly.
