### PR TITLE
fix(proxy): stop /{provider}/v1/files from capturing /anthropic passthrough

### LINKED ISSUE #37289: [Bug]: /{provider}/v1/files shadows the /anthropic passthrough → 422 "purpose Field required"
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

Same shadowing as #36086, on a different prefix. #36092 fixed `/openai_passthrough` and states
"other provider prefixes keep today's behavior" — `/anthropic` is still affected on `main`.

- `POST /anthropic/v1/files` is answered by LiteLLM's OpenAI files endpoint instead of being
  forwarded, and fails `422 {"loc":["body","purpose"],"msg":"Field required"}`
- `purpose` is OpenAI-only. Anthropic's Files API has no such field, so the Anthropic SDK never
  sends one — `client.beta.files.upload({ file })` has no `purpose` param. The request cannot succeed
- Adding `purpose` doesn't help: that path 500s on `files_settings is not set`
- Regressed in v1.92.0 via [#30958](https://github.com/BerriAI/litellm/pull/30958/files#diff-cb47ff448a23857ca19cd50f8baa9aea47ee5cdefb475803fdc022449dc10d7eR15624),
  which moved `batches_router` and `openai_files_router` above the passthrough routers in
  `proxy_server.py`. Worked on v1.83.14-stable, where the order was reversed
- `POST /anthropic/v1/files/` (trailing slash) is forwarded correctly, so it's route precedence,
  not the body

Expected: `/anthropic/v1/files` forwards to `api.anthropic.com/v1/files` like every other path
under `/anthropic/`.

### User Flow

Before: a developer using the Anthropic SDK against the gateway cannot upload a document at all, so
the model never sees their PDF.

1. They set base URL `https://litellm-domain/anthropic` and send
   `POST https://litellm-domain/anthropic/v1/files` with `file=@plan.pdf` — what
   `client.beta.files.upload({ file })` emits
2. They get `422 {"detail":[{"type":"missing","loc":["body","purpose"],"msg":"Field required"}]}`,
   no file id, and nothing in their Anthropic account
3. They add `purpose=user_data` and retry the same POST
4. They get `500 {"error":{"message":"files_settings is not set, set it on your config.yaml file."}}`
5. With no file id they cannot reference the document in
   `POST https://litellm-domain/anthropic/v1/messages`, so the answer ignores their PDF

After: the same upload returns an Anthropic file id and the model reads the document.

1. They set base URL `https://litellm-domain/anthropic` and send the same
   `POST https://litellm-domain/anthropic/v1/files` with `file=@plan.pdf`, no extra fields
2. They get `200` with Anthropic's own file object —
   `{"type":"file","id":"file_011Ce8...","mime_type":"application/pdf"}` — visible in their account
3. They send `POST https://litellm-domain/anthropic/v1/messages` with a `document` block using that
   `file_id`
4. They get `200` and the reply quotes the PDF's contents

### Proof the bug occurs

`config.yaml`:

```yaml
model_list:
  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/claude-haiku-4-5
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  master_key: sk-local-repro-master
```

Env: `ANTHROPIC_API_KEY=sk-ant-invalid-key-for-local-repro`, `CONFIG_FILE_PATH=./config.yaml`,
`LITELLM_MASTER_KEY=sk-local-repro-master`

Version: `litellm==1.96.2`, run as
`python -m uvicorn litellm.proxy.proxy_server:app --host 127.0.0.1 --port 4000`

The Anthropic key is invalid on purpose — it makes routing unambiguous for free. A request LiteLLM
answers itself fails 422 on `purpose`; a request that is forwarded fails 401 at Anthropic.

1. What the SDK sends — intercepted, never forwarded:

```
$ curl -s -w "\nHTTP %{http_code}\n" -X POST http://127.0.0.1:4000/anthropic/v1/files \
    -H "x-api-key: $MASTER_KEY" -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: files-api-2025-04-14" -F "file=@repro.pdf;type=application/pdf"

{"detail":[{"type":"missing","loc":["body","purpose"],"msg":"Field required","input":null}]}
HTTP 422
```

2. Trailing slash — forwarded, 401 from Anthropic as expected with an invalid key:

```
$ curl -s -w "\nHTTP %{http_code}\n" -X POST http://127.0.0.1:4000/anthropic/v1/files/ \
    -H "x-api-key: $MASTER_KEY" -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: files-api-2025-04-14" -F "file=@repro.pdf;type=application/pdf"

{"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}
HTTP 401
```

3. Control — `/anthropic/v1/messages` forwards normally, same 401:

```
$ curl -s -X POST http://127.0.0.1:4000/anthropic/v1/messages \
    -H "x-api-key: $MASTER_KEY" -H "anthropic-version: 2023-06-01" \
    -H "content-type: application/json" \
    -d '{"model":"claude-haiku-4-5","max_tokens":16,"messages":[{"role":"user","content":"hi"}]}'

{"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}
HTTP 401
```

2 and 3 prove the passthrough is wired correctly; 1 differs only in path shape.

4. With a valid Anthropic key on a v1.96.2 gateway (key and host redacted), the trailing-slash path
completes the round trip:

```
POST /anthropic/v1/files/?beta=true
{"type":"file","id":"file_011CeAPEhuywu41e5rH8h3Dp","size_bytes":401,
 "created_at":"2026-08-18T14:37:54.596000Z","filename":"repro.pdf",
 "mime_type":"application/pdf","downloadable":false}
HTTP 200

POST /anthropic/v1/messages   (document block referencing that file_id)
{"content":[{"type":"text","text":"passthrough round trip ok"}],"stop_reason":"end_turn"}
```

"passthrough round trip ok" is the literal text in the uploaded PDF, so the model read the document.

# Suggested fix

- give `/anthropic` its own router mounted ahead of batches and files, as #36092 did for
  `/openai_passthrough`
- or scope `/{provider}/v1/files` so it cannot shadow a registered passthrough prefix, which covers
  every provider whose native API has no `purpose`

### What part of LiteLLM is this about?

Proxy

### What LiteLLM version are you on ?

v1.96.2

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by chelsealong**
## TLDR

Problem this solves:

- `/anthropic/v1/files` 422s on OpenAI-only `purpose` instead of forwarding to Anthropic
- Same route-shadowing bug #36092 fixed for `/openai_passthrough`, now on `/anthropic`

How it solves it:

- give `/anthropic` its own router, mounted ahead of the batches and files routers
- every other provider prefix keeps today's behavior

## User Flow

Before: a developer using the Anthropic SDK against the gateway cannot upload a document at all, so the model never sees their PDF

1. They set base URL `https://litellm-domain/anthropic` and send `POST https://litellm-domain/anthropic/v1/files` with `file=@plan.pdf`, what `client.beta.files.upload({ file })` emits
2. They get `422 {"detail":[{"type":"missing","loc":["body","purpose"],"msg":"Field required"}]}`, no file id, and nothing in their Anthropic account
3. With no file id they cannot reference the document in `POST https://litellm-domain/anthropic/v1/messages`, so the answer ignores their PDF

After: the same upload reaches Anthropic instead of being intercepted locally

1. They set base URL `https://litellm-domain/anthropic` and send the same `POST https://litellm-domain/anthropic/v1/files` with `file=@plan.pdf`, no extra fields
2. The request reaches `api.anthropic.com`, so with a valid key they get back Anthropic's own file object and can reference its `file_id` in a later `/anthropic/v1/messages` call

## Relevant issues

Fixes #37289

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [x] I have added meaningful tests
- [x] My PR passes all CI/CD checks (e.g., lint, format, unit tests)
- [x] My PR's scope is as isolated as possible; it only solves 1 specific problem
- [ ] I have received a Greptile **Confidence Score of at least 4/5** before requesting a maintainer review (Greptile reviews automatically once the PR is opened; only comment `@greptileai` to re-request a review after pushing changes)

## Delays in PR merge?

If you're seeing a delay in your PR being merged, ping the LiteLLM Team on [Slack (#pr-review)](https://join.slack.com/t/litellmossslack/shared_invite/zt-3o7nkuyfr-p_kbNJj8taRfXGgQI1~YyA).

## Screenshots / Proof of Fix

Config used for both runs:

```yaml
model_list:
  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/claude-haiku-4-5
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  master_key: sk-local-repro-master
```

Run with `ANTHROPIC_API_KEY=sk-ant-invalid-key-for-local-repro` on purpose, same technique as the issue: a request LiteLLM answers itself fails 422 on `purpose`, a request that is forwarded to Anthropic fails 401 there instead.

### Before (41de13aa0c)

1. `POST /anthropic/v1/files`:

```
$ curl -s -w "\nHTTP %{http_code}\n" -X POST http://127.0.0.1:4000/anthropic/v1/files \
    -H "x-api-key: sk-local-repro-master" -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: files-api-2025-04-14" -F "file=@repro.pdf;type=application/pdf"

{"detail":[{"type":"missing","loc":["body","purpose"],"msg":"Field required","input":null}]}
HTTP 422
```

### After (75fbc4b481)

1. `POST /anthropic/v1/files`, now forwarded, 401 from Anthropic as expected with an invalid key:

```
$ curl -s -w "\nHTTP %{http_code}\n" -X POST http://127.0.0.1:4000/anthropic/v1/files \
    -H "x-api-key: sk-local-repro-master" -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: files-api-2025-04-14" -F "file=@repro.pdf;type=application/pdf"

{"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}
HTTP 401
```

2. Control, `/anthropic/v1/messages` still forwards normally, same 401:

```
$ curl -s -X POST http://127.0.0.1:4000/anthropic/v1/messages \
    -H "x-api-key: sk-local-repro-master" -H "anthropic-version: 2023-06-01" \
    -H "content-type: application/json" \
    -d '{"model":"claude-haiku-4-5","max_tokens":16,"messages":[{"role":"user","content":"hi"}]}'

{"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}
HTTP 401
```

Unit test proof, `git checkout HEAD~1 -- litellm/proxy/pass_through_endpoints/llm_passthrough_endpoints.py litellm/proxy/proxy_server.py` then running the new test:

```
$ uv run pytest tests/test_litellm/proxy/pass_through_endpoints/test_llm_pass_through_endpoints.py -k test_anthropic_passthrough_prefix_wins_over_native_provider_routes -q
...
FAILED ...[DELETE-/anthropic/v1/files/file-abc123] - AssertionError: assert 'delete_file' == 'anthropic_proxy_route'
FAILED ...[GET-/anthropic/v1/files/file-abc123] - AssertionError: assert 'get_file' == 'anthropic_proxy_route'
FAILED ...[GET-/anthropic/v1/files] - AssertionError: assert 'list_files' == 'anthropic_proxy_route'
FAILED ...[POST-/anthropic/v1/batches] - AssertionError: assert 'create_batch' == 'anthropic_proxy_route'
FAILED ...[POST-/anthropic/v1/files] - AssertionError: assert 'create_file' == 'anthropic_proxy_route'
5 failed, 1 passed, 132 deselected, 1 warning in 5.39s
```

Restoring the fix and re-running the full file:

```
$ uv run pytest tests/test_litellm/proxy/pass_through_endpoints/test_llm_pass_through_endpoints.py -q
...
138 passed, 3 warnings in 5.64s
```

## Type

🐛 Bug Fix

### Final Attestation

- [x] The tests check the right things, including the edge cases, and regressions in the respective real-world customer use-cases are not possible after this PR

### CODE REVIEW

**Comment by IdoPort** [comment]
Hitting the same symptom sequence (422 missing `purpose` → 500 `files_settings is not set`), but from a setup this issue won't fix, so flagging the gap:

**Our case:** we're not proxying to direct `api.anthropic.com` — we're relaying to a distinct Anthropic-compatible endpoint (Claude Platform on AWS), which needs its own `target`/`api_base` and an extra `anthropic-workspace-id` header alongside `x-api-key`. That's only configurable via an explicit `pass_through_endpoints` entry in `config.yaml`, not via the built-in `/anthropic/{endpoint:path}` catch-all (which is hardcoded to `ANTHROPIC_API_BASE`/`ANTHROPIC_BASE_URL` defaulting to `api.anthropic.com`, and to a plain `ANTHROPIC_API_KEY`).

Since the built-in catch-all owns the literal `/anthropic` prefix unconditionally, using a custom `pass_through_endpoints` config for a *different* Anthropic-compatible target means the prefix has to be something other than `/anthropic` (e.g. `/claude-aws`) — otherwise our config-declared target/headers are silently ignored and every request goes to `api.anthropic.com` with the wrong key instead.

But moving to a non-`/anthropic` prefix reproduces exactly this issue's shadowing: `POST /claude-aws/v1/files` still gets caught by `/{provider}/v1/files`, 422s on `purpose`, then 500s on `files_settings not set`.

The description says "every other provider prefix keeps today's behavior" — meaning even once merged, this specific case (a **custom** prefix pointing at a **non-default** Anthropic-compatible endpoint via `pass_through_endpoints`) stays broken, since the fix only re-privileges the literal `/anthropic` path.

**Version note:** we're seeing this on `litellm==1.87.0` (PyPI upload `2026-06-02`), which predates PR #30958 (merged `2026-07-02`, blamed for the regression) by a full month — so either the regression predates that PR, or there's a second root cause with an identical symptom on older versions.

**Ask:** would it be possible to generalize the fix so any path explicitly declared in `pass_through_endpoints` always takes precedence over the generic `/{provider}/v1/files` (and batches) routers, rather than special-casing just `/anthropic`? That would cover custom-provider passthrough configs like ours without needing a per-prefix carve-out for every non-default endpoint.

Happy to provide a minimal repro `config.yaml` if useful.

**Comment by chelsealong** [comment]
That's a separate root cause: custom pass_through_endpoints prefixes, not the /anthropic catch-all this PR fixes. Please file a new issue for it.

**Comment by IdoPort** [comment]
Filed as #37925 — thanks for the quick triage.
