### ISSUE TITLE
For Cohere, got error: dict object has no attribute 'choices'

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#150]
To reproduce:

```python
def test_completion_cohere_choice():
    try:
        response = completion(model="command-nightly", messages=messages)
        response_str = response.choices[0].message.content
        assert type(response_str) == str
        assert len(response_str) > 1
    except Exception as e:
        pytest.fail(f"Error occurred: {e}")
 ```

**Comment by yujonglee** [comment]
That test fails on master branch, but calling `response.choices[0].message.content` works fine in `0.1.426`. Maybe I am missing something...

**Comment by ghost** [comment]
That's odd - I believe we're testing for this on circle ci in our `test_completions`.. Will investigate and push a fix

**Comment by ghost** [comment]
Thanks for the great work @yujonglee

**Comment by ishaan-jaff** [comment]
<img width="605" alt="Screenshot 2023-08-19 at 4 22 28 PM" src="https://github.com/BerriAI/litellm/assets/29436595/ff122050-b8a6-4ba3-99bc-a8b146927783">


works fine for me 0.1.426

where does it fail for you @yujonglee ?

**Comment by ishaan-jaff** [comment]
master is in sync with 0.1.426 too

**Comment by ishaan-jaff** [comment]
<img width="834" alt="Screenshot 2023-08-19 at 4 25 26 PM" src="https://github.com/BerriAI/litellm/assets/29436595/30c581cd-6f34-40f3-bad6-1176f386e252">

also ran the test on the main branch - worked fine

**Comment by ghost** [comment]
closing as this seems to be fixed
